"""Generate the frozen sync golden vectors in ``spec/sync/``.

Run once, by hand, and never again as part of a test or a CI job::

    cd backend && uv run python tools/generate_sync_vectors.py

The point of the vectors is that they are *frozen*: the Python codec and the
Dart codec both assert byte equality against the same committed file, so a
change on either side that the other did not make shows up as a failing test
rather than as two implementations quietly agreeing on something new.  A
generator wired into the test run would defeat that entirely — it would
regenerate the expectation to match whatever the Python side now does.

Re-running this script is therefore a deliberate protocol change.  Expect the
diff to be reviewed as one.
"""

from __future__ import annotations

import hashlib
import json
import struct
import sys
import uuid
from dataclasses import replace
from pathlib import Path
from typing import Any

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from nacl.signing import SigningKey  # noqa: E402

from app.sync.control_payload import (  # noqa: E402
    COMPACTION_EXEMPT_OP_CLASSES,
    CONTROL_TYPE_GRANT,
    CONTROL_TYPE_MEMBER_REGISTER,
    CONTROL_TYPE_REVOKE,
    CONTROL_TYPE_WORKSPACE_GENESIS,
    GRANTER_ROOT,
    KEX_PUBLIC_KEY_BYTES,
    KNOWN_ROLES,
    MEMBER_KIND_DEVICE,
    MEMBER_KIND_SERVICE,
    PREV_CONTROL_HASH_BYTES,
    ROLE_OP_CLASS_MATRIX,
    ROLE_OWNER,
    ROLE_PARTICIPANT,
    ROLE_SUGGESTER,
    SERVED_CONTROL_TYPES,
    SIGNING_DOMAIN_GRANT_V1,
    SIGNING_DOMAIN_MEMBER_REGISTER_V1,
    SIGNING_DOMAIN_REVOKE_V1,
    SIGNING_DOMAIN_WORKSPACE_GENESIS_V1,
    ZERO_PREV_CONTROL_HASH,
    ControlPayload,
    GenesisCertificate,
    GrantCertificate,
    MemberKeys,
    RegistrationCertificate,
    RevokeCertificate,
    control_payload_hash,
    sign_genesis_certificate,
    sign_grant_certificate,
    sign_registration_certificate,
    sign_revoke_certificate,
)
from app.sync.envelope import (  # noqa: E402
    BODY_OVERSIZE_MULTIPLE_BYTES,
    BODY_SIZE_CLASSES_BYTES,
    ENVELOPE_OVERHEAD_BYTES,
    HEADER_FIELD_LAYOUT,
    HEADER_LENGTH_BYTES,
    KNOWN_OP_CLASSES,
    OP_CLASS_COMPACTION,
    OP_CLASS_CONTENT,
    OP_CLASS_CONTROL,
    PAYLOAD_LENGTH_PREFIX_BYTES,
    SERVED_OP_CLASSES,
    SERVED_SUITES,
    SIGNATURE_LENGTH_BYTES,
    SIGNING_DOMAIN_OP_V1,
    SUITE_AEAD_V1,
    SUITE_PLAINTEXT_V1,
    OpHeader,
    build_envelope,
    derive_key_id,
    envelope_hash,
    frame_body,
)
from app.sync.escrow import (  # noqa: E402
    ARGON2ID_FLOOR_MEMORY_KIB,
    ARGON2ID_FLOOR_PARALLELISM,
    ARGON2ID_FLOOR_TIME_COST,
    ESCROW_BLOB_BYTES,
    ESCROW_BLOB_HEADER_BYTES,
    ESCROW_BLOB_MAGIC,
    ESCROW_NONCE_BYTES,
    ESCROW_SALT_BYTES,
    ESCROW_SECRET_BYTES,
    FIRST_ESCROW_VERSION,
    POLY1305_TAG_BYTES,
    SIGNING_DOMAIN_ESCROW_V1,
    escrow_signing_input,
    sign_escrow,
)
from app.sync.ids import (  # noqa: E402
    JEEVES_WORKSPACE_NAMESPACE,
    USER_PREFERENCES_COLLECTION,
    USER_PREFERENCES_WORKSPACE_NAMESPACE,
    default_workspace_id,
    preference_entity_id,
    user_preferences_workspace_id,
)
from app.sync.member_auth import (  # noqa: E402
    MEMBER_CHALLENGE_NONCE_BYTES,
    SIGNING_DOMAIN_AUTH_CHALLENGE_V1,
    member_challenge_signing_input,
)
from app.sync.op_payload import FieldWrite, Hlc, OpPayload  # noqa: E402

SPEC_DIR = Path(__file__).resolve().parents[2] / "spec" / "sync"

FROZEN_NOTICE = (
    "FROZEN. Generated once by backend/tools/generate_sync_vectors.py and "
    "asserted byte-for-byte by both backend/tests/sync/ and app/test/sync/. "
    "Never regenerated by a test or by CI: regenerating is a protocol change."
)

# --- Fixed spec identities --------------------------------------------------

SPEC_USER_ID = "spec-user-1"
SPEC_OTHER_USER_ID = "spec-user-2"
WORKSPACE_ID = default_workspace_id(SPEC_USER_ID)
OTHER_WORKSPACE_ID = default_workspace_id(SPEC_OTHER_USER_ID)
#: The implicit User-global preferences Workspace: every Device, no Service ever.
PREFERENCES_WORKSPACE_ID = user_preferences_workspace_id(SPEC_USER_ID)

KEY_LABELS = ("device_a", "device_b")


def _seed(label: str) -> bytes:
    return hashlib.sha256(f"jeeves/spec/sync/seed/{label}".encode()).digest()


def _member_id(label: str) -> uuid.UUID:
    return uuid.uuid5(JEEVES_WORKSPACE_NAMESPACE, f"spec/member/{label}")


def _op_id(name: str) -> uuid.UUID:
    return uuid.uuid5(JEEVES_WORKSPACE_NAMESPACE, f"spec/op/{name}")


def _grant_id(name: str) -> uuid.UUID:
    return uuid.uuid5(JEEVES_WORKSPACE_NAMESPACE, f"spec/grant/{name}")


def _revoke_id(name: str) -> uuid.UUID:
    return uuid.uuid5(JEEVES_WORKSPACE_NAMESPACE, f"spec/revoke/{name}")


#: A Grant carries **no key material** — that is the whole point of the
#: Grant/KeyWrap split (F19) — so a grantee the vectors only ever *name* needs no
#: keypair.  This one stands in for a Service that an owning Device grants the
#: suggester role to, and it is deliberately synthetic: nothing here signs.
SUGGESTER_MEMBER_ID = _member_id("suggester_service")


SIGNING_KEYS = {label: SigningKey(_seed(label)) for label in KEY_LABELS}
MEMBER_IDS = {label: _member_id(label) for label in KEY_LABELS}

#: The spec Workspace's Root.  Never a member, never an envelope author: it signs
#: registration certificates and the escrow record, and nothing else.  In
#: production Root is random and lives only in the escrow (review F1); here it is
#: seeded so the certificates below are reproducible.
ROOT_SIGNING_KEY = SigningKey(_seed("root"))
ROOT_PUBLIC_KEY = bytes(ROOT_SIGNING_KEY.verify_key)

#: X25519 keys are pinned as raw bytes rather than derived from a seed: the two
#: codecs only ever carry them, and neither derives one.
KEX_PUBLIC_KEYS = {
    label: hashlib.sha256(f"jeeves/spec/sync/kex/{label}".encode()).digest() for label in KEY_LABELS
}

THEME_KEY = "theme"
THEME_ENTITY_ID = preference_entity_id(WORKSPACE_ID, THEME_KEY)

BASE_WALL_MS = 1_800_000_000_000


# --- Builders ---------------------------------------------------------------


def _header(
    *,
    op_id_name: str,
    key: str,
    author_seq: int,
    suite: int = SUITE_PLAINTEXT_V1,
    op_class: int = OP_CLASS_CONTENT,
    workspace_id: uuid.UUID = WORKSPACE_ID,
    prev_author_hash: bytes | None = None,
) -> OpHeader:
    sign_pk = bytes(SIGNING_KEYS[key].verify_key)
    return OpHeader(
        suite=suite,
        op_class=op_class,
        workspace_id=workspace_id,
        key_epoch=0,
        op_id=_op_id(op_id_name),
        author_member_id=MEMBER_IDS[key],
        author_key_id=derive_key_id(sign_pk),
        author_seq=author_seq,
        prev_author_hash=prev_author_hash or bytes(32),
    )


def _header_json(header: OpHeader) -> dict[str, Any]:
    return {
        "suite": header.suite,
        "op_class": header.op_class,
        "workspace_id": str(header.workspace_id),
        "key_epoch": header.key_epoch,
        "op_id": str(header.op_id),
        "author_member_id": str(header.author_member_id),
        "author_key_id_hex": header.author_key_id.hex(),
        "author_seq": header.author_seq,
        "prev_author_hash_hex": header.prev_author_hash.hex(),
        "observed_head_hex": header.observed_head.hex(),
        "nonce_hex": header.nonce.hex(),
    }


#: Padding a size-class vector's body carries beyond its framed payload.
#:
#: Spelled out because the note text on those vectors states this number, and the
#: payload length is ``size_class - PAYLOAD_LENGTH_PREFIX_BYTES - this``.  Left as
#: a bare ``- 36`` the two halves could not move together: a change to the prefix
#: width would silently produce vectors whose own notes were wrong.
PADDING_BYTES_IN_SIZE_CLASS_VECTORS = 32


def _sized_payload(base: OpPayload, target_payload_length: int) -> OpPayload:
    """``base`` grown with an ASCII filler field to exactly the target length."""
    probe = replace(base, fields={**base.fields, "filler": FieldWrite(value="")})
    padding_needed = target_payload_length - len(probe.encode())
    if padding_needed < 0:
        raise ValueError(f"base payload already exceeds {target_payload_length} bytes")
    return replace(base, fields={**base.fields, "filler": FieldWrite(value="x" * padding_needed)})


def _positive(
    name: str,
    *,
    key: str,
    header: OpHeader,
    payload: bytes,
    note: str,
) -> dict[str, Any]:
    body = frame_body(payload)
    envelope = build_envelope(header, body, SIGNING_KEYS[key])
    return {
        "name": name,
        "note": note,
        "key": key,
        "header": _header_json(header),
        "header_hex": header.serialize().hex(),
        "payload_json": payload.decode("utf-8"),
        "payload_length_bytes": len(payload),
        "body_length_bytes": len(body),
        "body_hex": body.hex(),
        "signature_hex": envelope[-SIGNATURE_LENGTH_BYTES:].hex(),
        "envelope_hex": envelope.hex(),
        "envelope_sha256_hex": envelope_hash(envelope).hex(),
    }


def _negative(
    name: str,
    *,
    key: str,
    reason: str,
    envelope: bytes,
    note: str,
    expected_workspace_id: uuid.UUID = WORKSPACE_ID,
) -> dict[str, Any]:
    return {
        "name": name,
        "note": note,
        "key": key,
        "reason": reason,
        "expected_workspace_id": str(expected_workspace_id),
        "envelope_hex": envelope.hex(),
    }


def _theme_payload(*, key: str, value: str, wall_ms: int, counter: int = 0) -> OpPayload:
    return OpPayload(
        collection=USER_PREFERENCES_COLLECTION,
        entity_id=THEME_ENTITY_ID,
        hlc=Hlc.for_member(MEMBER_IDS[key], wall_ms, counter),
        fields={
            "key": FieldWrite(value=THEME_KEY),
            "value": FieldWrite(value=json.dumps(value)),
        },
    )


# --- Vector sets ------------------------------------------------------------


def _header_vectors() -> list[dict[str, Any]]:
    """Header-only vectors that pin each field to its offset.

    The probe is deliberately not a servable op: every field carries a distinct
    byte pattern so that a codec reading a field at the wrong offset produces
    visibly wrong bytes rather than a plausible-looking header.
    """
    all_zero = OpHeader(
        suite=0,
        op_class=0,
        workspace_id=uuid.UUID(int=0),
        key_epoch=0,
        op_id=uuid.UUID(int=0),
        author_member_id=uuid.UUID(int=0),
        author_key_id=bytes(8),
        author_seq=0,
    )
    probe = OpHeader(
        suite=0xA1,
        op_class=0xA2,
        workspace_id=uuid.UUID(bytes=b"\x11" * 16),
        key_epoch=0xB3B4B5B6,
        op_id=uuid.UUID(bytes=b"\x22" * 16),
        author_member_id=uuid.UUID(bytes=b"\x33" * 16),
        author_key_id=b"\x44" * 8,
        # Distinct in every byte that can be, and below 2^53 so a JSON reader
        # on a platform without a 64-bit integer type still round-trips it
        # exactly (see MAX_REPRESENTABLE_AUTHOR_SEQ on the Dart side).
        author_seq=0x001F2F3F4F5F6F7F,
        prev_author_hash=b"\x55" * 32,
        observed_head=b"\x66" * 32,
        nonce=b"\x77" * 24,
    )
    return [
        {
            "name": "all_zero_header",
            "note": "158 zero bytes — pins the header length itself.",
            "header": _header_json(all_zero),
            "header_hex": all_zero.serialize().hex(),
        },
        {
            "name": "distinct_field_probe",
            "note": "Every field a distinct byte pattern — pins every offset.",
            "header": _header_json(probe),
            "header_hex": probe.serialize().hex(),
        },
    ]


def _positive_vectors() -> list[dict[str, Any]]:
    vectors: list[dict[str, Any]] = []

    first_header = _header(op_id_name="set_theme_dark", key="device_a", author_seq=1)
    first = _positive(
        "content_set_preference",
        key="device_a",
        header=first_header,
        payload=_theme_payload(key="device_a", value="dark", wall_ms=BASE_WALL_MS).encode(),
        note="The smallest real op: one user_preferences write, body in the 256 class.",
    )
    vectors.append(first)

    chained_header = _header(
        op_id_name="set_theme_light",
        key="device_a",
        author_seq=2,
        prev_author_hash=bytes.fromhex(first["envelope_sha256_hex"]),
    )
    vectors.append(
        _positive(
            "content_chained_author_seq_2",
            key="device_a",
            header=chained_header,
            payload=_theme_payload(
                key="device_a", value="light", wall_ms=BASE_WALL_MS + 1000
            ).encode(),
            note=(
                "author_seq 2 with prev_author_hash = SHA-256 of "
                "content_set_preference's envelope — pins the per-author chain."
            ),
        )
    )

    vectors.append(
        _positive(
            "content_tombstone",
            key="device_b",
            header=_header(op_id_name="delete_theme", key="device_b", author_seq=1),
            payload=OpPayload(
                collection=USER_PREFERENCES_COLLECTION,
                entity_id=THEME_ENTITY_ID,
                hlc=Hlc.for_member(MEMBER_IDS["device_b"], BASE_WALL_MS + 2000),
                tombstone=True,
            ).encode(),
            note="Deletion is an op, never row absence: empty fields plus tombstone.",
        )
    )

    vectors.append(
        _positive(
            "content_per_field_hlc",
            key="device_a",
            header=_header(op_id_name="per_field_hlc", key="device_a", author_seq=3),
            payload=OpPayload(
                collection=USER_PREFERENCES_COLLECTION,
                entity_id=THEME_ENTITY_ID,
                hlc=Hlc.for_member(MEMBER_IDS["device_a"], BASE_WALL_MS + 3000),
                fields={
                    "key": FieldWrite(value=THEME_KEY),
                    "value": FieldWrite(
                        value='"solarized"',
                        hlc=Hlc.for_member(MEMBER_IDS["device_b"], BASE_WALL_MS - 5000),
                    ),
                },
            ).encode(),
            note=(
                "Per-field HLC capability: format now, populated only by "
                "compaction ops (#555) re-asserting original clocks."
            ),
        )
    )

    for index, size_class in enumerate(BODY_SIZE_CLASSES_BYTES):
        vectors.append(
            _positive(
                f"content_body_size_class_{size_class}",
                key="device_a",
                header=_header(
                    op_id_name=f"size_class_{size_class}", key="device_a", author_seq=10 + index
                ),
                payload=_sized_payload(
                    _theme_payload(key="device_a", value="dark", wall_ms=BASE_WALL_MS),
                    size_class - PAYLOAD_LENGTH_PREFIX_BYTES - PADDING_BYTES_IN_SIZE_CLASS_VECTORS,
                ).encode(),
                note=(
                    f"Body padded to the {size_class}-byte size class, "
                    f"{PADDING_BYTES_IN_SIZE_CLASS_VECTORS} padding bytes."
                ),
            )
        )

    oversize_body_length = 2 * BODY_OVERSIZE_MULTIPLE_BYTES
    vectors.append(
        _positive(
            "content_body_oversize_32768",
            key="device_a",
            header=_header(op_id_name="oversize", key="device_a", author_seq=20),
            payload=_sized_payload(
                _theme_payload(key="device_a", value="dark", wall_ms=BASE_WALL_MS),
                oversize_body_length
                - PAYLOAD_LENGTH_PREFIX_BYTES
                - PADDING_BYTES_IN_SIZE_CLASS_VECTORS,
            ).encode(),
            note=(
                "Above the largest size class a body rounds up to the next "
                "16 KiB multiple, with no hard cap."
            ),
        )
    )

    return vectors


def _negative_vectors() -> list[dict[str, Any]]:
    payload = _theme_payload(key="device_a", value="dark", wall_ms=BASE_WALL_MS).encode()
    body = frame_body(payload)
    vectors: list[dict[str, Any]] = []

    vectors.append(
        _negative(
            "unknown_suite",
            key="device_a",
            reason="unsupported_suite",
            envelope=build_envelope(
                _header(op_id_name="unknown_suite", key="device_a", author_seq=1, suite=0x7F),
                body,
                SIGNING_KEYS["device_a"],
            ),
            note="Suite 0x7F is not a value the protocol names. Fail closed (F21).",
        )
    )
    vectors.append(
        _negative(
            "unknown_op_class",
            key="device_a",
            reason="unsupported_op_class",
            envelope=build_envelope(
                _header(op_id_name="unknown_op_class", key="device_a", author_seq=1, op_class=9),
                body,
                SIGNING_KEYS["device_a"],
            ),
            note="op_class 9 is outside 1-5. Fail closed.",
        )
    )
    vectors.append(
        _negative(
            "unimplemented_op_class_compaction",
            key="device_a",
            reason="unsupported_op_class",
            envelope=build_envelope(
                _header(
                    op_id_name="unimplemented_op_class",
                    key="device_a",
                    author_seq=1,
                    op_class=OP_CLASS_COMPACTION,
                ),
                body,
                SIGNING_KEYS["device_a"],
            ),
            note=(
                "op_class 4 is a named class this slice does not implement. It "
                "quarantines on the same surface as an unknown value; #555 turns "
                "this into a positive vector."
            ),
        )
    )

    valid = build_envelope(
        _header(op_id_name="set_theme_dark", key="device_a", author_seq=1),
        body,
        SIGNING_KEYS["device_a"],
    )
    vectors.append(
        _negative(
            "truncated_header",
            key="device_a",
            reason="truncated_envelope",
            envelope=valid[: HEADER_LENGTH_BYTES - 1],
            note=f"One byte short of the {HEADER_LENGTH_BYTES}-byte header.",
        )
    )
    vectors.append(
        _negative(
            "truncated_envelope_no_body",
            key="device_a",
            reason="truncated_envelope",
            envelope=valid[:ENVELOPE_OVERHEAD_BYTES],
            note=f"Exactly the {ENVELOPE_OVERHEAD_BYTES}-byte overhead: no body at all.",
        )
    )
    vectors.append(
        _negative(
            "bad_signature",
            key="device_a",
            reason="bad_signature",
            envelope=valid[:-1] + bytes([valid[-1] ^ 0x01]),
            note="Last signature byte flipped; header and body untouched.",
        )
    )

    padding_start = PAYLOAD_LENGTH_PREFIX_BYTES + len(payload)
    tampered_padding = bytearray(body)
    tampered_padding[padding_start] = 0x01
    vectors.append(
        _negative(
            "non_zero_padding",
            key="device_a",
            reason="non_zero_padding",
            envelope=build_envelope(
                _header(op_id_name="non_zero_padding", key="device_a", author_seq=1),
                bytes(tampered_padding),
                SIGNING_KEYS["device_a"],
            ),
            note=(
                f"The non-zero byte sits at offset {padding_start} = "
                "4 + payload_len, the *first* padding position, so an "
                "off-by-one in the padding scan cannot pass this vector. "
                "Signed over the tampered body, so only the padding rule fires."
            ),
        )
    )

    illegal_length = 300
    illegal_body = bytearray(struct.pack(">I", len(payload)) + payload)
    illegal_body.extend(bytes(illegal_length - len(illegal_body)))
    vectors.append(
        _negative(
            "invalid_padded_length",
            key="device_a",
            reason="invalid_body_length",
            envelope=build_envelope(
                _header(op_id_name="invalid_padded_length", key="device_a", author_seq=1),
                bytes(illegal_body),
                SIGNING_KEYS["device_a"],
            ),
            note=(
                f"{illegal_length}-byte body: neither a size class nor a "
                f"{BODY_OVERSIZE_MULTIPLE_BYTES}-byte multiple."
            ),
        )
    )

    overrun_body = bytearray(body)
    overrun_body[:PAYLOAD_LENGTH_PREFIX_BYTES] = struct.pack(">I", len(body))
    vectors.append(
        _negative(
            "payload_overruns_body",
            key="device_a",
            reason="payload_overruns_body",
            envelope=build_envelope(
                _header(op_id_name="payload_overruns_body", key="device_a", author_seq=1),
                bytes(overrun_body),
                SIGNING_KEYS["device_a"],
            ),
            note=(
                "payload_len is the whole body length, so 4 + payload_len > "
                "body_len. The frame must be rejected before any byte of it is "
                "read as a payload."
            ),
        )
    )

    uppercase_payload = json.dumps(
        {
            "collection": USER_PREFERENCES_COLLECTION,
            "id": str(THEME_ENTITY_ID),
            "fields": {"value": {"v": '"dark"'}},
            "hlc": [BASE_WALL_MS, 0, MEMBER_IDS["device_a"].hex.upper()],
        },
        separators=(",", ":"),
    ).encode("utf-8")
    vectors.append(
        _negative(
            "uppercase_member_id_hex",
            key="device_a",
            reason="malformed_member_id_hex",
            envelope=build_envelope(
                _header(op_id_name="uppercase_member_id", key="device_a", author_seq=1),
                frame_body(uppercase_payload),
                SIGNING_KEYS["device_a"],
            ),
            note=(
                "HLC member ids are exactly 32 lowercase hex characters. The "
                "tie-break is a lexicographic string compare, so an uppercase "
                "id would order differently — codecs reject rather than "
                "normalise."
            ),
        )
    )

    malformed_entity_id_payload = json.dumps(
        {
            "collection": USER_PREFERENCES_COLLECTION,
            "id": str(THEME_ENTITY_ID).replace("-", ""),
            "fields": {"value": {"v": '"dark"'}},
            "hlc": [BASE_WALL_MS, 0, MEMBER_IDS["device_a"].hex],
        },
        separators=(",", ":"),
    ).encode("utf-8")
    vectors.append(
        _negative(
            "malformed_entity_id",
            key="device_a",
            reason="malformed_payload",
            envelope=build_envelope(
                _header(op_id_name="malformed_entity_id", key="device_a", author_seq=1),
                frame_body(malformed_entity_id_payload),
                SIGNING_KEYS["device_a"],
            ),
            note=(
                "The right 32 hex digits, dashes removed.  Python's `uuid.UUID` "
                "accepts this spelling and the Dart codec's `uuidToBytes` does "
                "not, so it is exactly the shape the two codecs used to "
                "disagree about.  Both now require the canonical lowercase "
                "8-4-4-4-12 form and reject the rest rather than normalising, "
                "as they do for an HLC member id."
            ),
        )
    )

    vectors.append(
        _negative(
            "workspace_mismatch",
            key="device_a",
            reason="workspace_mismatch",
            envelope=build_envelope(
                _header(
                    op_id_name="workspace_mismatch",
                    key="device_a",
                    author_seq=1,
                    workspace_id=OTHER_WORKSPACE_ID,
                ),
                body,
                SIGNING_KEYS["device_a"],
            ),
            note=(
                "Header workspace disagrees with the stream it arrived in: a "
                "server-integrity event, not a filtered row (F6). The "
                "plaintext-era analogue of 'AEAD failure is an alarm'."
            ),
        )
    )

    return vectors


# --- Control vectors (op_class = 2) -----------------------------------------


def _certificate(
    label: str, *, wall_ms: int, workspace_id: uuid.UUID = WORKSPACE_ID
) -> RegistrationCertificate:
    return RegistrationCertificate(
        workspace_id=workspace_id,
        member_id=MEMBER_IDS[label],
        sign_pk=bytes(SIGNING_KEYS[label].verify_key),
        kex_pk=KEX_PUBLIC_KEYS[label],
        registered_at_hlc=Hlc.for_member(MEMBER_IDS[label], wall_ms),
        member_kind=MEMBER_KIND_DEVICE,
    )


def _member_keys(label: str, *, member_kind: str = MEMBER_KIND_DEVICE) -> MemberKeys:
    return MemberKeys(
        member_id=MEMBER_IDS[label],
        sign_pk=bytes(SIGNING_KEYS[label].verify_key),
        kex_pk=KEX_PUBLIC_KEYS[label],
        member_kind=member_kind,
    )


def _control_vector(
    name: str,
    *,
    key: str,
    payload: ControlPayload,
    cert_json: str,
    author_seq: int,
    prev_author_hash: bytes | None = None,
    note: str,
) -> dict[str, Any]:
    payload_bytes = payload.encode()
    body = frame_body(payload_bytes)
    header = _header(
        op_id_name=f"control/{name}",
        key=key,
        author_seq=author_seq,
        op_class=OP_CLASS_CONTROL,
        prev_author_hash=prev_author_hash,
    )
    envelope = build_envelope(header, body, SIGNING_KEYS[key])
    return {
        "name": name,
        "note": note,
        "key": key,
        "header": _header_json(header),
        "header_hex": header.serialize().hex(),
        "control_type": payload.control_type,
        "prev_control_hash_hex": payload.prev_control_hash.hex(),
        # "root" for the two Root-only types and for a root-signed grant/revoke;
        # a member uuid when an owning Device signed it.  Which key verifies the
        # signature is decided by this field and nothing else.  Read back off the
        # decoded payload rather than off what was passed in, so the vector pins
        # what a *receiver* resolves — for the Root-only types that is "root"
        # whether or not the field is on the wire.
        "authority": ControlPayload.decode(payload_bytes).authority,
        "cert_json": cert_json,
        "cert_hex": payload.cert_bytes.hex(),
        "signature_hex": payload.signature.hex(),
        "payload_json": payload_bytes.decode("utf-8"),
        "payload_length_bytes": len(payload_bytes),
        # The cross-author chain link a successor names: SHA-256 over these
        # payload bytes, not over the envelope.
        "payload_sha256_hex": control_payload_hash(payload_bytes).hex(),
        "body_length_bytes": len(body),
        "body_hex": body.hex(),
        "envelope_hex": envelope.hex(),
        "envelope_sha256_hex": envelope_hash(envelope).hex(),
    }


def _genesis_payload(
    label: str, *, wall_ms: int, prev_control_hash: bytes = ZERO_PREV_CONTROL_HASH
) -> tuple[ControlPayload, str]:
    certificate = GenesisCertificate(
        workspace_id=WORKSPACE_ID,
        root_pk=ROOT_PUBLIC_KEY,
        founder=_member_keys(label),
        created_at_hlc=Hlc.for_member(MEMBER_IDS[label], wall_ms),
    )
    cert_bytes = certificate.encode()
    return (
        ControlPayload(
            control_type=CONTROL_TYPE_WORKSPACE_GENESIS,
            prev_control_hash=prev_control_hash,
            cert_bytes=cert_bytes,
            signature=sign_genesis_certificate(cert_bytes, ROOT_SIGNING_KEY),
        ),
        cert_bytes.decode("utf-8"),
    )


def _grant_payload(
    *,
    grant_name: str,
    member_id: uuid.UUID,
    role: str,
    granter: str,
    prev_control_hash: bytes,
    wall_ms: int,
    signing_key: SigningKey = ROOT_SIGNING_KEY,
    corrupt_signature: bool = False,
) -> tuple[ControlPayload, str]:
    certificate = GrantCertificate(
        workspace_id=WORKSPACE_ID,
        grant_id=_grant_id(grant_name),
        member_id=member_id,
        role=role,
        granter=granter,
        granted_at_hlc=Hlc.for_member(member_id, wall_ms),
    )
    cert_bytes = certificate.encode()
    signature = bytearray(sign_grant_certificate(cert_bytes, signing_key))
    if corrupt_signature:
        signature[-1] ^= 0x01
    return (
        ControlPayload(
            control_type=CONTROL_TYPE_GRANT,
            prev_control_hash=prev_control_hash,
            cert_bytes=cert_bytes,
            signature=bytes(signature),
            authority=granter,
        ),
        cert_bytes.decode("utf-8"),
    )


def _revoke_payload(
    *,
    revoke_name: str,
    grant_id: uuid.UUID,
    revoker: str,
    prev_control_hash: bytes,
    wall_ms: int,
    signing_key: SigningKey = ROOT_SIGNING_KEY,
    corrupt_signature: bool = False,
) -> tuple[ControlPayload, str]:
    revoke_id = _revoke_id(revoke_name)
    certificate = RevokeCertificate(
        workspace_id=WORKSPACE_ID,
        revoke_id=revoke_id,
        grant_id=grant_id,
        revoker=revoker,
        revoked_at_hlc=Hlc.for_member(revoke_id, wall_ms),
    )
    cert_bytes = certificate.encode()
    signature = bytearray(sign_revoke_certificate(cert_bytes, signing_key))
    if corrupt_signature:
        signature[-1] ^= 0x01
    return (
        ControlPayload(
            control_type=CONTROL_TYPE_REVOKE,
            prev_control_hash=prev_control_hash,
            cert_bytes=cert_bytes,
            signature=bytes(signature),
            authority=revoker,
        ),
        cert_bytes.decode("utf-8"),
    )


def _control_vectors() -> list[dict[str, Any]]:
    """One canonical control chain, in the order a real Workspace produces it.

    genesis -> the founder's root-signed owner Grant -> the second Device's
    ``member_register`` -> its root-signed owner Grant -> an owner-signed
    suggester Grant to a Service -> a root-signed Revoke of that Grant.

    Every link is pinned twice over: ``prev_control_hash`` chains the *control*
    ops across authors by payload hash, and ``prev_author_hash`` chains each
    author's own ops by envelope hash.  The two are deliberately different hashes
    over different bytes, and a codec that confused them would fail here.
    """
    vectors: list[dict[str, Any]] = []
    #: Per-author envelope-hash heads, so each author's chain is truthful.
    author_heads: dict[str, bytes] = {}
    author_seqs: dict[str, int] = {}

    def append(
        name: str,
        *,
        key: str,
        payload: ControlPayload,
        cert_json: str,
        note: str,
    ) -> dict[str, Any]:
        author_seqs[key] = author_seqs.get(key, 0) + 1
        vector = _control_vector(
            name,
            key=key,
            payload=payload,
            cert_json=cert_json,
            author_seq=author_seqs[key],
            prev_author_hash=author_heads.get(key),
            note=note,
        )
        author_heads[key] = bytes.fromhex(vector["envelope_sha256_hex"])
        vectors.append(vector)
        return vector

    genesis_payload, genesis_cert_json = _genesis_payload("device_a", wall_ms=BASE_WALL_MS)
    genesis = append(
        "workspace_genesis",
        key="device_a",
        payload=genesis_payload,
        cert_json=genesis_cert_json,
        note=(
            "The Workspace comes into being: author_seq 1, an all-zero "
            "prev_control_hash — the only op that may carry one — and a Root "
            "signature under jeeves/workspace-genesis/v1. The certificate embeds "
            "the founding Device's registration, because the envelope's author "
            "key is unknowable before the certificate parses and there is no "
            "earlier op to learn it from (ADR-0031). root_pk sits inside the "
            "signed bytes so every later verifier can cross-check the Root it "
            "pinned."
        ),
    )

    founder_grant_payload, founder_grant_cert_json = _grant_payload(
        grant_name="founder_owner",
        member_id=MEMBER_IDS["device_a"],
        role=ROLE_OWNER,
        granter=GRANTER_ROOT,
        prev_control_hash=bytes.fromhex(genesis["payload_sha256_hex"]),
        wall_ms=BASE_WALL_MS + 100,
    )
    founder_grant = append(
        "grant_founder_owner",
        key="device_a",
        payload=founder_grant_payload,
        cert_json=founder_grant_cert_json,
        note=(
            "Roles are one materialisation path: no implied grants, genesis "
            "included. The founder is an owner because Root said so in a "
            "separate signed fact, and revoking it later invalidates nothing "
            '(F14d). An owner role may only be minted with granter "root" — the '
            "mint half of the ceiling ADR-0031 records."
        ),
    )

    register_certificate = _certificate("device_b", wall_ms=BASE_WALL_MS + 1000)
    register_cert_bytes = register_certificate.encode()
    register = append(
        "member_register_second_device",
        key="device_b",
        payload=ControlPayload(
            control_type=CONTROL_TYPE_MEMBER_REGISTER,
            prev_control_hash=bytes.fromhex(founder_grant["payload_sha256_hex"]),
            cert_bytes=register_cert_bytes,
            signature=sign_registration_certificate(register_cert_bytes, ROOT_SIGNING_KEY),
        ),
        cert_json=register_cert_bytes.decode("utf-8"),
        note=(
            "The Nth Device's registration: its own author_seq 1, chained to the "
            "control head it observed by SHA-256 over that op's *payload bytes*, "
            "so the link is computable from the unencrypted payload alone and "
            "survives any future envelope-level re-framing. A zero link here "
            "would be refused even by an empty receiver — that is genesis-only."
        ),
    )

    second_grant_payload, second_grant_cert_json = _grant_payload(
        grant_name="second_device_owner",
        member_id=MEMBER_IDS["device_b"],
        role=ROLE_OWNER,
        granter=GRANTER_ROOT,
        prev_control_hash=bytes.fromhex(register["payload_sha256_hex"]),
        wall_ms=BASE_WALL_MS + 1100,
    )
    second_grant = append(
        "grant_second_device_owner",
        key="device_b",
        payload=second_grant_payload,
        cert_json=second_grant_cert_json,
        note=(
            "Devices are owners because the User acts through them, and the "
            "corollary is deliberate: revoking a Device takes the passphrase, "
            "because only Root can revoke an owner Grant."
        ),
    )

    suggester_grant_payload, suggester_grant_cert_json = _grant_payload(
        grant_name="service_suggester",
        member_id=SUGGESTER_MEMBER_ID,
        role=ROLE_SUGGESTER,
        granter=str(MEMBER_IDS["device_a"]),
        prev_control_hash=bytes.fromhex(second_grant["payload_sha256_hex"]),
        wall_ms=BASE_WALL_MS + 2000,
        signing_key=SIGNING_KEYS["device_a"],
    )
    suggester_grant = append(
        "grant_service_suggester_owner_signed",
        key="device_a",
        payload=suggester_grant_payload,
        cert_json=suggester_grant_cert_json,
        note=(
            "An owning Device granting a *non-owner* role, signed with its own "
            "key rather than Root's: the envelope author, the payload's granter "
            "and the certificate's granter are all the same member, because "
            "authority does not travel by courier. A Grant carries no key "
            "material, which is why the grantee here needs no keypair at all."
        ),
    )

    revoke_payload, revoke_cert_json = _revoke_payload(
        revoke_name="service_suggester",
        grant_id=_grant_id("service_suggester"),
        revoker=GRANTER_ROOT,
        prev_control_hash=bytes.fromhex(suggester_grant["payload_sha256_hex"]),
        wall_ms=BASE_WALL_MS + 3000,
    )
    append(
        "revoke_service_suggester",
        key="device_a",
        payload=revoke_payload,
        cert_json=revoke_cert_json,
        note=(
            "Revocation is grant-granular: the certificate names one grant_id, "
            "never a member (F19). Revoking the granter would not cascade — a "
            "fact valid at the position it was signed at stands, because nothing "
            "re-evaluates it (F14c)."
        ),
    )

    return vectors


def _negative_control_vectors() -> list[dict[str, Any]]:
    """Codec-level control rejections only.

    Anything needing receiver *state* is pinned by the route and harness tests
    instead: the position rule (``author_seq == 1``), the chain rule
    (``prev_control_hash`` against what has been applied), an unmaterialised
    grantee, a Service grant into the preferences Workspace, and the revoke half
    of the owner ceiling — that last one because the frozen revoke certificate
    names a ``grant_id``, so the target's role is state these bytes cannot carry.
    """
    cert = _certificate("device_a", wall_ms=BASE_WALL_MS)
    cert_bytes = cert.encode()
    good_signature = sign_registration_certificate(cert_bytes, ROOT_SIGNING_KEY)
    tampered = bytearray(good_signature)
    tampered[-1] ^= 0x01

    def control_negative(
        name: str,
        *,
        reason: str,
        payload: ControlPayload,
        note: str,
        key: str = "device_a",
        author_seq: int = 1,
    ) -> dict[str, Any]:
        return _negative(
            name,
            key=key,
            reason=reason,
            envelope=build_envelope(
                _header(
                    op_id_name=f"control/{name}",
                    key=key,
                    author_seq=author_seq,
                    op_class=OP_CLASS_CONTROL,
                ),
                frame_body(payload.encode()),
                SIGNING_KEYS[key],
            ),
            note=note,
        )

    genesis_payload, _ = _genesis_payload(
        "device_a", wall_ms=BASE_WALL_MS, prev_control_hash=hashlib.sha256(b"not-zero").digest()
    )
    non_root_owner_grant = GrantCertificate(
        workspace_id=WORKSPACE_ID,
        grant_id=_grant_id("member_minted_owner"),
        member_id=MEMBER_IDS["device_b"],
        role=ROLE_OWNER,
        granter=str(MEMBER_IDS["device_a"]),
        granted_at_hlc=Hlc.for_member(MEMBER_IDS["device_b"], BASE_WALL_MS + 4000),
    )
    # Built by hand: `GrantCertificate.decode` refuses this document, so
    # `encode()` is unreachable through the dataclass for exactly the shape the
    # vector has to carry.
    non_root_owner_cert_bytes = json.dumps(
        non_root_owner_grant.to_json_dict(), separators=(",", ":")
    ).encode("utf-8")
    unknown_role_cert_bytes = json.dumps(
        {
            **non_root_owner_grant.to_json_dict(),
            "grant_id": str(_grant_id("unknown_role")),
            "role": "archivist",
            "granter": GRANTER_ROOT,
        },
        separators=(",", ":"),
    ).encode("utf-8")
    missing_field_cert_bytes = json.dumps(
        {
            "workspace_id": str(WORKSPACE_ID),
            "grant_id": str(_grant_id("missing_member")),
            "role": ROLE_PARTICIPANT,
            "granter": GRANTER_ROOT,
            "granted_at_hlc": Hlc.for_member(MEMBER_IDS["device_b"], BASE_WALL_MS).to_json(),
        },
        separators=(",", ":"),
    ).encode("utf-8")

    good_grant_payload, _ = _grant_payload(
        grant_name="bad_granter_signature",
        member_id=MEMBER_IDS["device_b"],
        role=ROLE_PARTICIPANT,
        granter=GRANTER_ROOT,
        prev_control_hash=hashlib.sha256(b"predecessor").digest(),
        wall_ms=BASE_WALL_MS + 5000,
        corrupt_signature=True,
    )
    bad_revoke_payload, _ = _revoke_payload(
        revoke_name="bad_revoker_signature",
        grant_id=_grant_id("service_suggester"),
        revoker=GRANTER_ROOT,
        prev_control_hash=hashlib.sha256(b"predecessor").digest(),
        wall_ms=BASE_WALL_MS + 6000,
        corrupt_signature=True,
    )

    return [
        control_negative(
            "control_bad_root_signature",
            reason="bad_root_signature",
            payload=ControlPayload(
                control_type=CONTROL_TYPE_MEMBER_REGISTER,
                prev_control_hash=hashlib.sha256(b"predecessor").digest(),
                cert_bytes=cert_bytes,
                signature=bytes(tampered),
            ),
            note=(
                "Last byte of the Root signature flipped; the envelope itself is "
                "validly signed by the device. Without Root behind it a "
                "certificate is a claim, not a registration."
            ),
        ),
        control_negative(
            "control_unsupported_type",
            reason="unsupported_control_type",
            payload=ControlPayload(
                control_type="rotate",
                prev_control_hash=hashlib.sha256(b"predecessor").digest(),
            ),
            note=(
                "A control type this build does not serve. #554 turns `rotate` "
                "into a positive vector; until then every type outside the four "
                "served ones is fail-closed."
            ),
        ),
        control_negative(
            "control_malformed_payload",
            reason="malformed_control_payload",
            payload=ControlPayload(
                control_type=CONTROL_TYPE_MEMBER_REGISTER,
                prev_control_hash=ZERO_PREV_CONTROL_HASH,
            ),
            note=(
                "A served type with an empty certificate and an empty signature: "
                "the self-identifying fields parse and nothing else does."
            ),
        ),
        _negative(
            "control_no_type_field",
            key="device_a",
            reason="malformed_control_payload",
            envelope=build_envelope(
                _header(
                    op_id_name="control/no_type_field",
                    key="device_a",
                    author_seq=1,
                    op_class=OP_CLASS_CONTROL,
                ),
                frame_body(b'{"prev_control_hash":"00"}'),
                SIGNING_KEYS["device_a"],
            ),
            note=(
                "No `type` field and a short chain hash. Every control payload "
                "must be self-identifying: a chain link points at bare payload "
                "bytes, so nothing outside the payload can say what it is."
            ),
        ),
        control_negative(
            "control_member_register_with_zero_chain_link",
            reason="control_chain_break",
            payload=ControlPayload(
                control_type=CONTROL_TYPE_MEMBER_REGISTER,
                prev_control_hash=ZERO_PREV_CONTROL_HASH,
                cert_bytes=cert_bytes,
                signature=good_signature,
            ),
            note=(
                "An all-zero prev_control_hash is **genesis-only** (ADR-0031). "
                "Refused even by a receiver whose control state is empty, which "
                "is what makes a truncated history always detectable: treating a "
                "zero link as 'fresh chain' is exactly the claim a server "
                "serving a truncated log makes."
            ),
        ),
        control_negative(
            "control_genesis_with_a_non_zero_chain_link",
            reason="control_chain_break",
            payload=genesis_payload,
            note=(
                "The mirror rule: genesis is the Workspace's *first* control op, "
                "so it must carry the zero link and nothing else. A genesis "
                "naming a predecessor is a second genesis wearing a chain."
            ),
        ),
        control_negative(
            "control_grant_bad_granter_signature",
            reason="bad_grant_signature",
            payload=good_grant_payload,
            note=(
                "Last byte of the granter's signature flipped. Authority rides "
                "in the signed certificate bytes, so an unsigned Grant is a "
                "request rather than a fact."
            ),
        ),
        control_negative(
            "control_revoke_bad_revoker_signature",
            reason="bad_revoke_signature",
            payload=bad_revoke_payload,
            note=(
                "The same rule on the unmaking side, under its own domain: a "
                "signature made over a Grant must never verify over a Revoke."
            ),
        ),
        control_negative(
            "control_grant_unknown_role",
            reason="unknown_role",
            payload=ControlPayload(
                control_type=CONTROL_TYPE_GRANT,
                prev_control_hash=hashlib.sha256(b"predecessor").digest(),
                cert_bytes=unknown_role_cert_bytes,
                signature=sign_grant_certificate(unknown_role_cert_bytes, ROOT_SIGNING_KEY),
                authority=GRANTER_ROOT,
            ),
            note=(
                "A role outside owner/participant/compactor/suggester, validly "
                "Root-signed. It still fails closed: a role a verifier cannot "
                "interpret must never be read as a permissive default."
            ),
        ),
        control_negative(
            "control_grant_owner_role_minted_by_a_member",
            reason="owner_grant_requires_root",
            payload=ControlPayload(
                control_type=CONTROL_TYPE_GRANT,
                prev_control_hash=hashlib.sha256(b"predecessor").digest(),
                cert_bytes=non_root_owner_cert_bytes,
                signature=sign_grant_certificate(
                    non_root_owner_cert_bytes, SIGNING_KEYS["device_a"]
                ),
                authority=str(MEMBER_IDS["device_a"]),
            ),
            note=(
                "The mint half of the owner ceiling, and a pure document "
                "invariant: `role: owner` under any granter but Root is refused "
                "at decode, wherever the bytes are held. ADR-0031 records why "
                "the ceiling is symmetric with revocation — an owner-mints-owner "
                "rule would let a compromised device create an attacker-owner "
                "cheaply while removing one still cost the passphrase, and that "
                "asymmetry favours the attacker."
            ),
        ),
        control_negative(
            "control_grant_certificate_missing_member_id",
            reason="malformed_control_payload",
            payload=ControlPayload(
                control_type=CONTROL_TYPE_GRANT,
                prev_control_hash=hashlib.sha256(b"predecessor").digest(),
                cert_bytes=missing_field_cert_bytes,
                signature=sign_grant_certificate(missing_field_cert_bytes, ROOT_SIGNING_KEY),
                authority=GRANTER_ROOT,
            ),
            note=(
                "A Root-signed Grant with no grantee. A valid signature over an "
                "incomplete document authenticates the bytes and says nothing "
                "about their meaning, so the field rules run anyway."
            ),
        ),
    ]


# --- Escrow and challenge preimages -----------------------------------------

#: A deterministic stand-in for a real wrapped blob.  The server never parses a
#: blob and neither does this file — what the vectors pin is the *signature
#: preimage* around it, so the bytes only have to be reproducible.
_SPEC_ESCROW_BLOB = (
    ESCROW_BLOB_MAGIC
    + ARGON2ID_FLOOR_MEMORY_KIB.to_bytes(4, "big")
    + ARGON2ID_FLOOR_TIME_COST.to_bytes(4, "big")
    + bytes([ARGON2ID_FLOOR_PARALLELISM])
    + hashlib.sha256(b"jeeves/spec/sync/escrow/salt").digest()[:ESCROW_SALT_BYTES]
    + hashlib.sha256(b"jeeves/spec/sync/escrow/nonce").digest()[:ESCROW_NONCE_BYTES]
    + hashlib.sha512(b"jeeves/spec/sync/escrow/ciphertext").digest()[
        : ESCROW_SECRET_BYTES + POLY1305_TAG_BYTES
    ]
)


def _escrow_vectors() -> list[dict[str, Any]]:
    vectors: list[dict[str, Any]] = []
    for version, note in (
        (
            FIRST_ESCROW_VERSION,
            "The first write. workspace_id sits inside the signed bytes, so a "
            "blob signed for one Workspace can never be replayed into another.",
        ),
        (
            2,
            "A passphrase change re-wraps at v+1. The version is inside the "
            "preimage too, so a signature does not transfer between versions.",
        ),
    ):
        vectors.append(
            {
                "name": f"escrow_v1_signature_version_{version}",
                "note": note,
                "workspace_id": str(WORKSPACE_ID),
                "version": version,
                "blob_hex": _SPEC_ESCROW_BLOB.hex(),
                "signing_input_hex": escrow_signing_input(
                    WORKSPACE_ID, version, _SPEC_ESCROW_BLOB
                ).hex(),
                "root_sig_hex": sign_escrow(
                    WORKSPACE_ID, version, _SPEC_ESCROW_BLOB, ROOT_SIGNING_KEY
                ).hex(),
            }
        )
    return vectors


def _member_challenge_vectors() -> list[dict[str, Any]]:
    nonce = hashlib.sha256(b"jeeves/spec/sync/challenge/nonce").digest()[
        :MEMBER_CHALLENGE_NONCE_BYTES
    ]
    signing_input = member_challenge_signing_input(MEMBER_IDS["device_a"], nonce)
    return [
        {
            "name": "auth_challenge_v1",
            "note": (
                "The member id is inside the signed bytes, so a captured "
                "signature cannot be replayed into another member's slot."
            ),
            "key": "device_a",
            "member_id": str(MEMBER_IDS["device_a"]),
            "nonce_hex": nonce.hex(),
            "signing_input_hex": signing_input.hex(),
            "signature_hex": SIGNING_KEYS["device_a"].sign(signing_input).signature.hex(),
        }
    ]


def _envelope_vectors_document() -> dict[str, Any]:
    return {
        "$frozen": FROZEN_NOTICE,
        "protocol": {
            "header_length_bytes": HEADER_LENGTH_BYTES,
            "signature_length_bytes": SIGNATURE_LENGTH_BYTES,
            "envelope_overhead_bytes": ENVELOPE_OVERHEAD_BYTES,
            "signing_domain": SIGNING_DOMAIN_OP_V1.decode("ascii"),
            "signing_domain_hex": SIGNING_DOMAIN_OP_V1.hex(),
            "header_field_layout": [
                {"name": name, "offset": offset, "length_bytes": length}
                for name, offset, length in HEADER_FIELD_LAYOUT
            ],
            "suites": {
                "plaintext_v1": SUITE_PLAINTEXT_V1,
                "aead_v1_reserved": SUITE_AEAD_V1,
            },
            "served_suites": sorted(SERVED_SUITES),
            "op_classes": {
                "content": 1,
                "control": 2,
                "suggestion": 3,
                "compaction": 4,
                "prune": 5,
            },
            "known_op_classes": sorted(KNOWN_OP_CLASSES),
            "served_op_classes": sorted(SERVED_OP_CLASSES),
            "payload_length_prefix_bytes": PAYLOAD_LENGTH_PREFIX_BYTES,
            "body_size_classes_bytes": list(BODY_SIZE_CLASSES_BYTES),
            "body_oversize_multiple_bytes": BODY_OVERSIZE_MULTIPLE_BYTES,
            "workspace_namespace_uuid": str(JEEVES_WORKSPACE_NAMESPACE),
            "user_preferences_workspace_namespace_uuid": str(USER_PREFERENCES_WORKSPACE_NAMESPACE),
            # Every signing use of every key is domain-separated (review F7).
            "signing_domains": {
                "op_v1": SIGNING_DOMAIN_OP_V1.decode("ascii"),
                "member_register_v1": SIGNING_DOMAIN_MEMBER_REGISTER_V1.decode("ascii"),
                "workspace_genesis_v1": SIGNING_DOMAIN_WORKSPACE_GENESIS_V1.decode("ascii"),
                "grant_v1": SIGNING_DOMAIN_GRANT_V1.decode("ascii"),
                "revoke_v1": SIGNING_DOMAIN_REVOKE_V1.decode("ascii"),
                "auth_challenge_v1": SIGNING_DOMAIN_AUTH_CHALLENGE_V1.decode("ascii"),
                "escrow_v1": SIGNING_DOMAIN_ESCROW_V1.decode("ascii"),
            },
            "control": {
                "member_register_type": CONTROL_TYPE_MEMBER_REGISTER,
                "workspace_genesis_type": CONTROL_TYPE_WORKSPACE_GENESIS,
                "grant_type": CONTROL_TYPE_GRANT,
                "revoke_type": CONTROL_TYPE_REVOKE,
                "served_control_types": sorted(SERVED_CONTROL_TYPES),
                "member_kind_device": MEMBER_KIND_DEVICE,
                "member_kind_service": MEMBER_KIND_SERVICE,
                "prev_control_hash_bytes": PREV_CONTROL_HASH_BYTES,
                "zero_prev_control_hash_hex": ZERO_PREV_CONTROL_HASH.hex(),
                "kex_public_key_bytes": KEX_PUBLIC_KEY_BYTES,
                "chain_link": (
                    "SHA-256 over the predecessor control op's unframed payload "
                    "bytes — not the envelope, not a re-serialization."
                ),
                "zero_chain_link_rule": (
                    "An all-zero prev_control_hash is legal only on a "
                    "workspace_genesis. Every other control type carrying one is "
                    "refused as control_chain_break, even by a receiver whose "
                    "control state is empty — which is what makes a truncated "
                    "history always detectable."
                ),
                "granter_root": GRANTER_ROOT,
                "roles": list(KNOWN_ROLES),
                # Rows for op classes this build does not *serve* are defined
                # anyway, so #555 and #557 turn a class on by widening
                # SERVED_OP_CLASSES rather than by inventing a policy.
                "role_op_class_matrix": {
                    str(op_class): sorted(roles)
                    for op_class, roles in sorted(ROLE_OP_CLASS_MATRIX.items())
                },
                "owner_authority_ceiling": (
                    'An owner Grant may only be minted with granter "root" and '
                    'only be revoked with revoker "root". The symmetry is '
                    "deliberate (ADR-0031): an owner-mints-owner rule would let a "
                    "compromised device create an attacker-owner cheaply while "
                    "removing one still cost the passphrase."
                ),
                "compaction_exempt_op_classes": sorted(COMPACTION_EXEMPT_OP_CLASSES),
                "compaction_exemption_rule": (
                    "Control ops are never folded into a compaction op, and "
                    "neither are prune ops: compacting a control op away would "
                    "delete the evidence a Grant ever existed, and a prune op is "
                    "itself the attestation that history was removed. #555 "
                    "enforces this."
                ),
            },
            "escrow": {
                "blob_magic": ESCROW_BLOB_MAGIC.decode("ascii"),
                "blob_magic_hex": ESCROW_BLOB_MAGIC.hex(),
                "salt_bytes": ESCROW_SALT_BYTES,
                "nonce_bytes": ESCROW_NONCE_BYTES,
                "secret_bytes": ESCROW_SECRET_BYTES,
                "poly1305_tag_bytes": POLY1305_TAG_BYTES,
                "blob_header_bytes": ESCROW_BLOB_HEADER_BYTES,
                "blob_bytes": ESCROW_BLOB_BYTES,
                "first_version": FIRST_ESCROW_VERSION,
                # Enforced on read *and* write, before any KDF work runs (F12).
                "argon2id_floor": {
                    "memory_kib": ARGON2ID_FLOOR_MEMORY_KIB,
                    "time_cost": ARGON2ID_FLOOR_TIME_COST,
                    "parallelism": ARGON2ID_FLOOR_PARALLELISM,
                },
                "signing_preimage": (
                    'b"jeeves/escrow/v1" || workspace_id (16 raw bytes) || '
                    "version (u64 big-endian) || blob"
                ),
                "blob_layout": (
                    'magic "JVE1" 4B || m_cost_kib u32 || t_cost u32 || '
                    "parallelism u8 || salt 16B || nonce 24B || "
                    "XChaCha20-Poly1305(Argon2id(passphrase, salt, params), nonce, "
                    "aad = the 53 header bytes, root_sk 32B || master_wrap_key 32B)"
                ),
            },
            "member_challenge": {
                "nonce_bytes": MEMBER_CHALLENGE_NONCE_BYTES,
                "signing_preimage": (
                    'b"jeeves/auth-challenge/v1" || member_id (16 raw bytes) || nonce'
                ),
            },
        },
        "identities": {
            "user_id": SPEC_USER_ID,
            "workspace_id": str(WORKSPACE_ID),
            # The second implicit Workspace of the same User: User-global
            # preferences, every Device granted and no Service ever.  Derivation
            # keeps N devices agreeing on the id with no round-trip; the genesis
            # op is what makes its existence a signed fact.
            "user_preferences_workspace_id": str(PREFERENCES_WORKSPACE_ID),
            "other_user_id": SPEC_OTHER_USER_ID,
            "other_workspace_id": str(OTHER_WORKSPACE_ID),
            "preference_key": THEME_KEY,
            "preference_entity_id": str(THEME_ENTITY_ID),
            # Named by a Grant and nothing else: a Grant carries no key material,
            # so a grantee the vectors only name needs no keypair (F19).
            "suggester_member_id": str(SUGGESTER_MEMBER_ID),
            # Root is random in production and lives only inside the escrow blob
            # (review F1).  Seeding it here is what makes the certificates below
            # reproducible; nothing derives Root from anything.
            "root": {
                "seed_hex": _seed("root").hex(),
                "root_pk_hex": ROOT_PUBLIC_KEY.hex(),
            },
            "keys": [
                {
                    "label": label,
                    "member_id": str(MEMBER_IDS[label]),
                    "seed_hex": _seed(label).hex(),
                    "sign_pk_hex": bytes(SIGNING_KEYS[label].verify_key).hex(),
                    "key_id_hex": derive_key_id(bytes(SIGNING_KEYS[label].verify_key)).hex(),
                    "kex_pk_hex": KEX_PUBLIC_KEYS[label].hex(),
                }
                for label in KEY_LABELS
            ],
        },
        "header_vectors": _header_vectors(),
        "vectors": _positive_vectors(),
        "negative_vectors": _negative_vectors(),
        "control_vectors": _control_vectors(),
        "negative_control_vectors": _negative_control_vectors(),
        "escrow_vectors": _escrow_vectors(),
        "member_challenge_vectors": _member_challenge_vectors(),
    }


# --- Reducer vectors --------------------------------------------------------

_HARNESS_COLLECTION = "harness_docs"
_DOC_ID = str(uuid.uuid5(JEEVES_WORKSPACE_NAMESPACE, "spec/entity/harness_doc"))
_MEMBER_A = MEMBER_IDS["device_a"].hex
_MEMBER_B = MEMBER_IDS["device_b"].hex
# device_a and device_b must sort in a known direction for the tie-break case.
_LOWER_MEMBER, _HIGHER_MEMBER = sorted((_MEMBER_A, _MEMBER_B))

# --- #550: junction identity and the merge-strategy lattice ------------------

_TODO_TAGS_COLLECTION = "todo_tags"
_JUNCTION_TODO_ID = str(uuid.uuid5(JEEVES_WORKSPACE_NAMESPACE, "spec/entity/junction_todo"))
_JUNCTION_TAG_ID = str(uuid.uuid5(JEEVES_WORKSPACE_NAMESPACE, "spec/entity/junction_tag"))
_JUNCTION_USER_ID = "spec-user-1"
# The shipped `todoTagIdFor` derivation: uuid5(NAMESPACE_URL, "jeeves://todo_tag/<todo>/<tag>").
_JUNCTION_ID = str(
    uuid.uuid5(uuid.NAMESPACE_URL, f"jeeves://todo_tag/{_JUNCTION_TODO_ID}/{_JUNCTION_TAG_ID}")
)
_JUNCTION_FIELDS = {
    "todo_id": {"v": _JUNCTION_TODO_ID},
    "tag_id": {"v": _JUNCTION_TAG_ID},
    "user_id": {"v": _JUNCTION_USER_ID},
}
_JUNCTION_LIVE = {
    "todo_id": _JUNCTION_TODO_ID,
    "tag_id": _JUNCTION_TAG_ID,
    "user_id": _JUNCTION_USER_ID,
}

# Any key ending in `snoozed_until` arbitrates by `max_timestamp_value`
# (`strategyForKey`, ADR-0011); `spec_set_merge` has no production strategy and
# is pinned through the per-case `strategy_overrides` escape hatch.
_SNOOZE_KEY = "nudge_snoozed_until"
_SNOOZE_ENTITY_ID = str(preference_entity_id(WORKSPACE_ID, _SNOOZE_KEY))
_SET_MERGE_KEY = "spec_set_merge"
_SET_MERGE_ENTITY_ID = str(preference_entity_id(WORKSPACE_ID, _SET_MERGE_KEY))

# Preference values are JSON-encoded strings, so the reduced value of a snooze
# floor is a string that itself holds JSON.
_FLOOR_EARLY = json.dumps("2026-01-01T00:00:00.000Z")
_FLOOR_LATE = json.dumps("2026-06-01T00:00:00.000Z")
_FLOOR_COMPACT = json.dumps("2026-01-01T00:00:00Z")
_FLOOR_PADDED = json.dumps("2026-01-01T00:00:00.000Z")
_UNPARSEABLE_LOW = json.dumps("aardvark")
_UNPARSEABLE_HIGH = json.dumps("zebra")


def _pref_op(
    *,
    author: str,
    wall_ms: int,
    counter: int = 0,
    entity_id: str = _SNOOZE_ENTITY_ID,
    key: str | None = _SNOOZE_KEY,
    value: str | None = None,
    tombstone: bool = False,
) -> dict[str, Any]:
    fields: dict[str, Any] = {}
    if key is not None:
        fields["key"] = {"v": key}
    if value is not None:
        fields["value"] = {"v": value}
    return _reduce_op(
        author=author,
        collection=USER_PREFERENCES_COLLECTION,
        entity_id=entity_id,
        hlc=[wall_ms, counter, author],
        fields=fields,
        tombstone=tombstone,
    )


def _reduce_op(
    *,
    author: str,
    collection: str = _HARNESS_COLLECTION,
    entity_id: str = _DOC_ID,
    hlc: list[Any],
    fields: dict[str, Any] | None = None,
    tombstone: bool = False,
) -> dict[str, Any]:
    payload: dict[str, Any] = {
        "collection": collection,
        "id": entity_id,
        "fields": fields or {},
        "hlc": hlc,
    }
    if tombstone:
        payload["tombstone"] = True
    return {"author_member_id_hex": author, "payload": payload}


def _reducer_vectors_document() -> dict[str, Any]:
    t = BASE_WALL_MS
    cases: list[dict[str, Any]] = [
        {
            "name": "single_write",
            "note": "The base case: one field, one HLC, one live entity.",
            "ops": [
                _reduce_op(
                    author=_MEMBER_A,
                    hlc=[t, 0, _MEMBER_A],
                    fields={"a": {"v": "first"}},
                )
            ],
            "expected_entities": {_HARNESS_COLLECTION: {_DOC_ID: {"a": "first"}}},
            "expected_quarantine_reasons": [],
        },
        {
            "name": "same_field_newer_hlc_wins",
            "note": "Applied in HLC order.",
            "ops": [
                _reduce_op(author=_MEMBER_A, hlc=[t, 0, _MEMBER_A], fields={"a": {"v": "older"}}),
                _reduce_op(
                    author=_MEMBER_B,
                    hlc=[t + 1000, 0, _MEMBER_B],
                    fields={"a": {"v": "newer"}},
                ),
            ],
            "expected_entities": {_HARNESS_COLLECTION: {_DOC_ID: {"a": "newer"}}},
            "expected_quarantine_reasons": [],
        },
        {
            "name": "same_field_older_hlc_loses_out_of_order",
            "note": "Same two ops, reversed arrival. Reduction is order-independent.",
            "ops": [
                _reduce_op(
                    author=_MEMBER_B,
                    hlc=[t + 1000, 0, _MEMBER_B],
                    fields={"a": {"v": "newer"}},
                ),
                _reduce_op(author=_MEMBER_A, hlc=[t, 0, _MEMBER_A], fields={"a": {"v": "older"}}),
            ],
            "expected_entities": {_HARNESS_COLLECTION: {_DOC_ID: {"a": "newer"}}},
            "expected_quarantine_reasons": [],
        },
        {
            "name": "field_grain_concurrent_different_fields_both_survive",
            "note": "AC 5: concurrent edits to different fields of one row both survive.",
            "ops": [
                _reduce_op(author=_MEMBER_A, hlc=[t, 0, _MEMBER_A], fields={"a": {"v": "from_a"}}),
                _reduce_op(author=_MEMBER_B, hlc=[t, 0, _MEMBER_B], fields={"b": {"v": "from_b"}}),
            ],
            "expected_entities": {_HARNESS_COLLECTION: {_DOC_ID: {"a": "from_a", "b": "from_b"}}},
            "expected_quarantine_reasons": [],
        },
        {
            "name": "equal_hlc_is_idempotent",
            "note": "A pulled echo of one's own op re-applies to the same state.",
            "ops": [
                _reduce_op(author=_MEMBER_A, hlc=[t, 0, _MEMBER_A], fields={"a": {"v": "once"}}),
                _reduce_op(author=_MEMBER_A, hlc=[t, 0, _MEMBER_A], fields={"a": {"v": "once"}}),
            ],
            "expected_entities": {_HARNESS_COLLECTION: {_DOC_ID: {"a": "once"}}},
            "expected_quarantine_reasons": [],
        },
        {
            "name": "member_id_breaks_the_tie",
            "note": (
                "Equal wall_ms and counter: the member id decides, by "
                "lexicographic compare of the 32-hex form."
            ),
            "ops": [
                _reduce_op(
                    author=_LOWER_MEMBER,
                    hlc=[t, 0, _LOWER_MEMBER],
                    fields={"a": {"v": "lower_member"}},
                ),
                _reduce_op(
                    author=_HIGHER_MEMBER,
                    hlc=[t, 0, _HIGHER_MEMBER],
                    fields={"a": {"v": "higher_member"}},
                ),
            ],
            "expected_entities": {_HARNESS_COLLECTION: {_DOC_ID: {"a": "higher_member"}}},
            "expected_quarantine_reasons": [],
        },
        {
            "name": "tombstone_absorbs_older_write",
            "note": "A field write older than the tombstone stays hidden.",
            "ops": [
                _reduce_op(author=_MEMBER_A, hlc=[t, 0, _MEMBER_A], fields={"a": {"v": "doomed"}}),
                _reduce_op(author=_MEMBER_B, hlc=[t + 1000, 0, _MEMBER_B], tombstone=True),
            ],
            "expected_entities": {_HARNESS_COLLECTION: {}},
            "expected_quarantine_reasons": [],
        },
        {
            "name": "tombstone_resurrection_by_newer_write",
            "note": (
                "The mirror case: a field write newer than the tombstone applies "
                "and revives the entity, with only that field live."
            ),
            "ops": [
                _reduce_op(author=_MEMBER_A, hlc=[t, 0, _MEMBER_A], fields={"a": {"v": "doomed"}}),
                _reduce_op(author=_MEMBER_B, hlc=[t + 1000, 0, _MEMBER_B], tombstone=True),
                _reduce_op(
                    author=_MEMBER_A,
                    hlc=[t + 2000, 0, _MEMBER_A],
                    fields={"b": {"v": "revived"}},
                ),
            ],
            "expected_entities": {_HARNESS_COLLECTION: {_DOC_ID: {"b": "revived"}}},
            "expected_quarantine_reasons": [],
        },
        {
            "name": "per_field_hlc_from_another_member_in_the_past_applies",
            "note": (
                "F15 scoping, as ruled for this slice: the future-clock and "
                "hlc-member-equals-author guards are scoped to the op-level HLC "
                "*only*. A per-field HLC naming a different member at an older "
                "wall_ms is legal — that is exactly what a compaction op (#555) "
                "will carry — so it applies rather than quarantining."
            ),
            "ops": [
                _reduce_op(
                    author=_MEMBER_A,
                    hlc=[t + 5000, 0, _MEMBER_A],
                    fields={
                        "a": {"v": "reasserted", "hlc": [t - 60000, 7, _MEMBER_B]},
                        "b": {"v": "fresh"},
                    },
                )
            ],
            "expected_entities": {
                _HARNESS_COLLECTION: {_DOC_ID: {"a": "reasserted", "b": "fresh"}}
            },
            "expected_quarantine_reasons": [],
        },
        {
            "name": "per_field_hlc_loses_to_a_newer_stored_clock",
            "note": (
                "The per-field exemption is from the *guards*, not from LWW: a "
                "re-asserted older clock still loses to a newer stored one."
            ),
            "ops": [
                _reduce_op(
                    author=_MEMBER_B,
                    hlc=[t + 1000, 0, _MEMBER_B],
                    fields={"a": {"v": "current"}},
                ),
                _reduce_op(
                    author=_MEMBER_A,
                    hlc=[t + 5000, 0, _MEMBER_A],
                    fields={"a": {"v": "stale_reassert", "hlc": [t, 0, _MEMBER_A]}},
                ),
            ],
            "expected_entities": {_HARNESS_COLLECTION: {_DOC_ID: {"a": "current"}}},
            "expected_quarantine_reasons": [],
        },
        {
            "name": "op_level_hlc_in_the_future_quarantines",
            "note": (
                "F15: an unbounded wall_ms would pin a field against every "
                "future edit. Beyond the skew bound the op quarantines whole."
            ),
            "ops": [
                _reduce_op(
                    author=_MEMBER_A,
                    hlc=[t + 3_600_000, 0, _MEMBER_A],
                    fields={"a": {"v": "from_the_future"}},
                )
            ],
            "expected_entities": {_HARNESS_COLLECTION: {}},
            "expected_quarantine_reasons": ["hlc_in_the_future"],
        },
        {
            "name": "op_level_hlc_member_not_author_quarantines",
            "note": (
                "F15: the op-level HLC member must be the header's author, or a "
                "member could win tie-breaks under someone else's identity."
            ),
            "ops": [
                _reduce_op(
                    author=_MEMBER_A,
                    hlc=[t, 0, _MEMBER_B],
                    fields={"a": {"v": "impersonated"}},
                )
            ],
            "expected_entities": {_HARNESS_COLLECTION: {}},
            "expected_quarantine_reasons": ["hlc_member_is_not_author"],
        },
        {
            "name": "quarantined_op_does_not_stop_the_stream",
            "note": "A bad op is set aside and surfaced; the next valid op still applies.",
            "ops": [
                _reduce_op(
                    author=_MEMBER_A,
                    hlc=[t + 3_600_000, 0, _MEMBER_A],
                    fields={"a": {"v": "from_the_future"}},
                ),
                _reduce_op(author=_MEMBER_B, hlc=[t, 0, _MEMBER_B], fields={"a": {"v": "sane"}}),
            ],
            "expected_entities": {_HARNESS_COLLECTION: {_DOC_ID: {"a": "sane"}}},
            "expected_quarantine_reasons": ["hlc_in_the_future"],
        },
    ]
    cases.extend(_collection_and_strategy_cases(t))
    return {
        "$frozen": FROZEN_NOTICE,
        "local_now_ms": BASE_WALL_MS,
        "future_skew_bound_ms": 300_000,
        "$note": (
            "Ops here are payload-level, paired with the header author the "
            "reducer's guards check against. Envelope framing is "
            "envelope_v1_vectors.json's job. 'expected_entities' lists the live "
            "fields of every live entity after applying the ops in order; an "
            "entity with no live field is absent from the map."
        ),
        "$case_schema": (
            "Optional per-case keys, both added by #550 and honoured by every "
            "runner. 'permute': apply the ops in every order and assert the "
            "reduced state is identical across all of them — a values-only "
            "pairwise case cannot catch an associativity failure. "
            "'expected_clocks': the stored per-field HLC as "
            "{collection: {entity_id: {field: [wall_ms, counter, member_hex]}}}, "
            "asserted against `field_clocks` regardless of tombstone "
            "visibility, because a non-LWW strategy joins the clock "
            "independently of the value and nothing else observes that. "
            "'strategy_overrides': {preference_key: strategy_name} for keys "
            "with no production strategy — today only 'set_merge', which is "
            "provisioned but unregistered."
        ),
        "cases": cases,
    }


def _collection_and_strategy_cases(t: int) -> list[dict[str, Any]]:
    """Junction identity, tombstone revival, and the ADR-0030 merge lattice."""
    return [
        {
            "name": "junction_revive_after_unassign",
            "note": (
                "A junction's entity id is the uuid5 of its pair, so re-assigning "
                "the same tag after an unassign revives the *same* entity rather "
                "than forking. The re-assertion is newer than the tombstone, so "
                "the row is live again."
            ),
            "permute": True,
            "ops": [
                _reduce_op(
                    author=_MEMBER_A,
                    collection=_TODO_TAGS_COLLECTION,
                    entity_id=_JUNCTION_ID,
                    hlc=[t, 0, _MEMBER_A],
                    fields=_JUNCTION_FIELDS,
                ),
                _reduce_op(
                    author=_MEMBER_B,
                    collection=_TODO_TAGS_COLLECTION,
                    entity_id=_JUNCTION_ID,
                    hlc=[t + 1000, 0, _MEMBER_B],
                    tombstone=True,
                ),
                _reduce_op(
                    author=_MEMBER_A,
                    collection=_TODO_TAGS_COLLECTION,
                    entity_id=_JUNCTION_ID,
                    hlc=[t + 2000, 0, _MEMBER_A],
                    fields=_JUNCTION_FIELDS,
                ),
            ],
            "expected_entities": {_TODO_TAGS_COLLECTION: {_JUNCTION_ID: _JUNCTION_LIVE}},
            "expected_clocks": {
                _TODO_TAGS_COLLECTION: {
                    _JUNCTION_ID: {
                        "todo_id": [t + 2000, 0, _MEMBER_A],
                        "tag_id": [t + 2000, 0, _MEMBER_A],
                        "user_id": [t + 2000, 0, _MEMBER_A],
                    }
                }
            },
            "expected_quarantine_reasons": [],
        },
        {
            "name": "junction_unassign_is_a_tombstone_not_absence",
            "note": (
                "Unassignment tombstones the pair. A replayed assertion older "
                "than the tombstone cannot resurrect it, in either arrival order."
            ),
            "permute": True,
            "ops": [
                _reduce_op(
                    author=_MEMBER_A,
                    collection=_TODO_TAGS_COLLECTION,
                    entity_id=_JUNCTION_ID,
                    hlc=[t, 0, _MEMBER_A],
                    fields=_JUNCTION_FIELDS,
                ),
                _reduce_op(
                    author=_MEMBER_B,
                    collection=_TODO_TAGS_COLLECTION,
                    entity_id=_JUNCTION_ID,
                    hlc=[t + 1000, 0, _MEMBER_B],
                    tombstone=True,
                ),
            ],
            "expected_entities": {_TODO_TAGS_COLLECTION: {}},
            "expected_clocks": {
                _TODO_TAGS_COLLECTION: {
                    _JUNCTION_ID: {
                        "todo_id": [t, 0, _MEMBER_A],
                        "tag_id": [t, 0, _MEMBER_A],
                        "user_id": [t, 0, _MEMBER_A],
                    }
                }
            },
            "expected_quarantine_reasons": [],
        },
        {
            "name": "max_timestamp_value_stale_later_value_wins",
            "note": (
                "The snooze floor: the value join is a total order on the value "
                "alone, so the later floor survives a newer write carrying an "
                "earlier one. The clock joins independently as the HLC max, "
                "which is why it belongs to the *losing* value here."
            ),
            "permute": True,
            "ops": [
                _pref_op(author=_MEMBER_A, wall_ms=t, value=_FLOOR_LATE),
                _pref_op(author=_MEMBER_B, wall_ms=t + 1000, value=_FLOOR_EARLY),
            ],
            "expected_entities": {
                USER_PREFERENCES_COLLECTION: {
                    _SNOOZE_ENTITY_ID: {"key": _SNOOZE_KEY, "value": _FLOOR_LATE}
                }
            },
            "expected_clocks": {
                USER_PREFERENCES_COLLECTION: {
                    _SNOOZE_ENTITY_ID: {
                        "key": [t + 1000, 0, _MEMBER_B],
                        "value": [t + 1000, 0, _MEMBER_B],
                    }
                }
            },
            "expected_quarantine_reasons": [],
        },
        {
            "name": "max_timestamp_value_instant_tie_breaks_on_canonical_bytes",
            "note": (
                "Two spellings of one instant. The tie falls to the greater "
                "canonical JSON encoding, byte-wise — '\"…:00Z\"' beats "
                "'\"…:00.000Z\"' because 'Z' > '.'. Total, so associative."
            ),
            "permute": True,
            "ops": [
                _pref_op(author=_MEMBER_A, wall_ms=t, value=_FLOOR_PADDED),
                _pref_op(author=_MEMBER_B, wall_ms=t + 1000, value=_FLOOR_COMPACT),
            ],
            "expected_entities": {
                USER_PREFERENCES_COLLECTION: {
                    _SNOOZE_ENTITY_ID: {"key": _SNOOZE_KEY, "value": _FLOOR_COMPACT}
                }
            },
            "expected_clocks": {
                USER_PREFERENCES_COLLECTION: {
                    _SNOOZE_ENTITY_ID: {
                        "key": [t + 1000, 0, _MEMBER_B],
                        "value": [t + 1000, 0, _MEMBER_B],
                    }
                }
            },
            "expected_quarantine_reasons": [],
        },
        {
            "name": "max_timestamp_value_unparseable_loses_to_parseable",
            "note": (
                "Any parseable timestamp outranks any unparseable value, "
                "whatever the clocks say — the newer write here is the "
                "unparseable one and still loses the value."
            ),
            "permute": True,
            "ops": [
                _pref_op(author=_MEMBER_A, wall_ms=t + 1000, value=_UNPARSEABLE_HIGH),
                _pref_op(author=_MEMBER_B, wall_ms=t, value=_FLOOR_EARLY),
            ],
            "expected_entities": {
                USER_PREFERENCES_COLLECTION: {
                    _SNOOZE_ENTITY_ID: {"key": _SNOOZE_KEY, "value": _FLOOR_EARLY}
                }
            },
            "expected_clocks": {
                USER_PREFERENCES_COLLECTION: {
                    _SNOOZE_ENTITY_ID: {
                        "key": [t + 1000, 0, _MEMBER_A],
                        "value": [t + 1000, 0, _MEMBER_A],
                    }
                }
            },
            "expected_quarantine_reasons": [],
        },
        {
            "name": "max_timestamp_value_all_unparseable_orders_by_bytes",
            "note": (
                "With nothing parseable the order is the canonical byte order, "
                "which keeps the join total rather than falling back to LWW — "
                "the fallback was the non-associative part."
            ),
            "permute": True,
            "ops": [
                _pref_op(author=_MEMBER_A, wall_ms=t + 1000, value=_UNPARSEABLE_LOW),
                _pref_op(author=_MEMBER_B, wall_ms=t, value=_UNPARSEABLE_HIGH),
            ],
            "expected_entities": {
                USER_PREFERENCES_COLLECTION: {
                    _SNOOZE_ENTITY_ID: {"key": _SNOOZE_KEY, "value": _UNPARSEABLE_HIGH}
                }
            },
            "expected_clocks": {
                USER_PREFERENCES_COLLECTION: {
                    _SNOOZE_ENTITY_ID: {
                        "key": [t + 1000, 0, _MEMBER_A],
                        "value": [t + 1000, 0, _MEMBER_A],
                    }
                }
            },
            "expected_quarantine_reasons": [],
        },
        {
            "name": "max_timestamp_value_clear_then_later_resnooze_revives",
            "note": (
                "Clear (a tombstone) then a re-snooze whose clock is newer: "
                "tombstone visibility still arbitrates by plain HLC, so the "
                "floor is live again."
            ),
            "permute": True,
            "ops": [
                _pref_op(author=_MEMBER_A, wall_ms=t, value=_FLOOR_EARLY),
                _pref_op(author=_MEMBER_B, wall_ms=t + 1000, key=None, tombstone=True),
                _pref_op(author=_MEMBER_A, wall_ms=t + 2000, value=_FLOOR_LATE),
            ],
            "expected_entities": {
                USER_PREFERENCES_COLLECTION: {
                    _SNOOZE_ENTITY_ID: {"key": _SNOOZE_KEY, "value": _FLOOR_LATE}
                }
            },
            "expected_clocks": {
                USER_PREFERENCES_COLLECTION: {
                    _SNOOZE_ENTITY_ID: {
                        "key": [t + 2000, 0, _MEMBER_A],
                        "value": [t + 2000, 0, _MEMBER_A],
                    }
                }
            },
            "expected_quarantine_reasons": [],
        },
        {
            "name": "max_timestamp_value_stale_clear_loses_to_resnooze",
            "note": "A clear older than the re-snooze cannot silence it.",
            "permute": True,
            "ops": [
                _pref_op(author=_MEMBER_A, wall_ms=t + 1000, value=_FLOOR_EARLY),
                _pref_op(author=_MEMBER_B, wall_ms=t, key=None, tombstone=True),
            ],
            "expected_entities": {
                USER_PREFERENCES_COLLECTION: {
                    _SNOOZE_ENTITY_ID: {"key": _SNOOZE_KEY, "value": _FLOOR_EARLY}
                }
            },
            "expected_clocks": {
                USER_PREFERENCES_COLLECTION: {
                    _SNOOZE_ENTITY_ID: {
                        "key": [t + 1000, 0, _MEMBER_A],
                        "value": [t + 1000, 0, _MEMBER_A],
                    }
                }
            },
            "expected_quarantine_reasons": [],
        },
        {
            "name": "max_timestamp_value_clear_then_earlier_resnooze_keeps_preclear_floor",
            "note": (
                "The owned divergence from ADR-0011's pairwise matrix (ADR-0030): "
                "the value join is a max over every value ever asserted, so a "
                "re-snooze carrying an *earlier* value after a clear revives the "
                "field at the pre-clear floor. The floor never shrinks through a "
                "clear — it errs toward longer silence and never re-fires early."
            ),
            "permute": True,
            "ops": [
                _pref_op(author=_MEMBER_A, wall_ms=t, value=_FLOOR_LATE),
                _pref_op(author=_MEMBER_B, wall_ms=t + 1000, key=None, tombstone=True),
                _pref_op(author=_MEMBER_A, wall_ms=t + 2000, value=_FLOOR_EARLY),
            ],
            "expected_entities": {
                USER_PREFERENCES_COLLECTION: {
                    _SNOOZE_ENTITY_ID: {"key": _SNOOZE_KEY, "value": _FLOOR_LATE}
                }
            },
            "expected_clocks": {
                USER_PREFERENCES_COLLECTION: {
                    _SNOOZE_ENTITY_ID: {
                        "key": [t + 2000, 0, _MEMBER_A],
                        "value": [t + 2000, 0, _MEMBER_A],
                    }
                }
            },
            "expected_quarantine_reasons": [],
        },
        {
            "name": "max_timestamp_value_three_op_associativity",
            "note": (
                "Mandatory associativity probe: three writes carrying a "
                "parsed-instant tie *and* an unparseable member, applied in all "
                "six orders. A pairwise vector cannot catch a non-associative "
                "join; this one can."
            ),
            "permute": True,
            "ops": [
                _pref_op(author=_MEMBER_A, wall_ms=t, value=_FLOOR_COMPACT),
                _pref_op(author=_MEMBER_B, wall_ms=t + 1000, value=_FLOOR_PADDED),
                _pref_op(author=_MEMBER_A, wall_ms=t + 2000, value=_UNPARSEABLE_HIGH),
            ],
            "expected_entities": {
                USER_PREFERENCES_COLLECTION: {
                    _SNOOZE_ENTITY_ID: {"key": _SNOOZE_KEY, "value": _FLOOR_COMPACT}
                }
            },
            "expected_clocks": {
                USER_PREFERENCES_COLLECTION: {
                    _SNOOZE_ENTITY_ID: {
                        "key": [t + 2000, 0, _MEMBER_A],
                        "value": [t + 2000, 0, _MEMBER_A],
                    }
                }
            },
            "expected_quarantine_reasons": [],
        },
        {
            "name": "set_merge_unions_concurrent_additions",
            "note": (
                "Concurrent additions on two devices both survive, sorted by "
                "canonical JSON encoding so the merged value is byte-identical "
                "everywhere rather than order-dependent."
            ),
            "permute": True,
            "strategy_overrides": {_SET_MERGE_KEY: "set_merge"},
            "ops": [
                _pref_op(
                    author=_MEMBER_A,
                    wall_ms=t,
                    entity_id=_SET_MERGE_ENTITY_ID,
                    key=_SET_MERGE_KEY,
                    value=json.dumps(["a", "c"], separators=(",", ":")),
                ),
                _pref_op(
                    author=_MEMBER_B,
                    wall_ms=t + 1000,
                    entity_id=_SET_MERGE_ENTITY_ID,
                    key=_SET_MERGE_KEY,
                    value=json.dumps(["b", "a"], separators=(",", ":")),
                ),
            ],
            "expected_entities": {
                USER_PREFERENCES_COLLECTION: {
                    _SET_MERGE_ENTITY_ID: {
                        "key": _SET_MERGE_KEY,
                        "value": json.dumps(["a", "b", "c"], separators=(",", ":")),
                    }
                }
            },
            "expected_clocks": {
                USER_PREFERENCES_COLLECTION: {
                    _SET_MERGE_ENTITY_ID: {
                        "key": [t + 1000, 0, _MEMBER_B],
                        "value": [t + 1000, 0, _MEMBER_B],
                    }
                }
            },
            "expected_quarantine_reasons": [],
        },
        {
            "name": "set_merge_three_op_associativity",
            "note": (
                "Three additions with an overlapping member, in all six orders — "
                "the same associativity requirement the timestamp join carries."
            ),
            "permute": True,
            "strategy_overrides": {_SET_MERGE_KEY: "set_merge"},
            "ops": [
                _pref_op(
                    author=_MEMBER_A,
                    wall_ms=t,
                    entity_id=_SET_MERGE_ENTITY_ID,
                    key=_SET_MERGE_KEY,
                    value=json.dumps(["b"], separators=(",", ":")),
                ),
                _pref_op(
                    author=_MEMBER_B,
                    wall_ms=t + 1000,
                    entity_id=_SET_MERGE_ENTITY_ID,
                    key=_SET_MERGE_KEY,
                    value=json.dumps(["a", "b"], separators=(",", ":")),
                ),
                _pref_op(
                    author=_MEMBER_A,
                    wall_ms=t + 2000,
                    entity_id=_SET_MERGE_ENTITY_ID,
                    key=_SET_MERGE_KEY,
                    value=json.dumps(["c"], separators=(",", ":")),
                ),
            ],
            "expected_entities": {
                USER_PREFERENCES_COLLECTION: {
                    _SET_MERGE_ENTITY_ID: {
                        "key": _SET_MERGE_KEY,
                        "value": json.dumps(["a", "b", "c"], separators=(",", ":")),
                    }
                }
            },
            "expected_clocks": {
                USER_PREFERENCES_COLLECTION: {
                    _SET_MERGE_ENTITY_ID: {
                        "key": [t + 2000, 0, _MEMBER_A],
                        "value": [t + 2000, 0, _MEMBER_A],
                    }
                }
            },
            "expected_quarantine_reasons": [],
        },
        {
            "name": "set_merge_unsorted_first_write_is_canonical_and_replay_safe",
            "note": (
                "ADR-0030(a) idempotence on a *non-canonical* input. The first "
                "write into an empty field has nothing to union with, so it is "
                "the one path that could store a caller's array in arrival "
                "order; the third op re-asserts that same op verbatim. Both the "
                "reduced value and its clock must be unmoved by the "
                "re-assertion, because that re-assertion is precisely what a "
                "#555 compaction op does to every value it carries forward."
            ),
            "permute": True,
            "strategy_overrides": {_SET_MERGE_KEY: "set_merge"},
            "ops": [
                _pref_op(
                    author=_MEMBER_A,
                    wall_ms=t,
                    entity_id=_SET_MERGE_ENTITY_ID,
                    key=_SET_MERGE_KEY,
                    value=json.dumps(["c", "a"], separators=(",", ":")),
                ),
                _pref_op(
                    author=_MEMBER_B,
                    wall_ms=t + 1000,
                    entity_id=_SET_MERGE_ENTITY_ID,
                    key=_SET_MERGE_KEY,
                    value=json.dumps(["b", "a"], separators=(",", ":")),
                ),
                # Byte-identical to the first op, clock included: a replay, not a
                # new write.
                _pref_op(
                    author=_MEMBER_A,
                    wall_ms=t,
                    entity_id=_SET_MERGE_ENTITY_ID,
                    key=_SET_MERGE_KEY,
                    value=json.dumps(["c", "a"], separators=(",", ":")),
                ),
            ],
            "expected_entities": {
                USER_PREFERENCES_COLLECTION: {
                    _SET_MERGE_ENTITY_ID: {
                        "key": _SET_MERGE_KEY,
                        "value": json.dumps(["a", "b", "c"], separators=(",", ":")),
                    }
                }
            },
            "expected_clocks": {
                USER_PREFERENCES_COLLECTION: {
                    _SET_MERGE_ENTITY_ID: {
                        "key": [t + 1000, 0, _MEMBER_B],
                        "value": [t + 1000, 0, _MEMBER_B],
                    }
                }
            },
            "expected_quarantine_reasons": [],
        },
        {
            "name": "strategy_selection_falls_back_to_lww_without_a_key",
            "note": (
                "A `user_preferences` op whose entity has no resolvable `key` — "
                "none carried, none stored — falls back to LWW. The newer clock "
                "wins even though its value is the earlier floor, which is the "
                "opposite of what max_timestamp_value would decide."
            ),
            "permute": True,
            "ops": [
                _pref_op(author=_MEMBER_A, wall_ms=t + 1000, key=None, value=_FLOOR_EARLY),
                _pref_op(author=_MEMBER_B, wall_ms=t, key=None, value=_FLOOR_LATE),
            ],
            "expected_entities": {
                USER_PREFERENCES_COLLECTION: {_SNOOZE_ENTITY_ID: {"value": _FLOOR_EARLY}}
            },
            "expected_clocks": {
                USER_PREFERENCES_COLLECTION: {
                    _SNOOZE_ENTITY_ID: {"value": [t + 1000, 0, _MEMBER_A]}
                }
            },
            "expected_quarantine_reasons": [],
        },
        {
            "name": "strategy_selection_reads_the_stored_key",
            "note": (
                "The strategy is selected per entity by its `key` field: an op "
                "that carries only `value` resolves the key from reduced state, "
                "and the floor still wins. Converges in either arrival order."
            ),
            "permute": True,
            "ops": [
                _pref_op(author=_MEMBER_A, wall_ms=t, value=_FLOOR_LATE),
                _pref_op(author=_MEMBER_B, wall_ms=t + 1000, key=None, value=_FLOOR_EARLY),
            ],
            "expected_entities": {
                USER_PREFERENCES_COLLECTION: {
                    _SNOOZE_ENTITY_ID: {"key": _SNOOZE_KEY, "value": _FLOOR_LATE}
                }
            },
            "expected_clocks": {
                USER_PREFERENCES_COLLECTION: {
                    _SNOOZE_ENTITY_ID: {
                        "key": [t, 0, _MEMBER_A],
                        "value": [t + 1000, 0, _MEMBER_B],
                    }
                }
            },
            "expected_quarantine_reasons": [],
        },
    ]


def main() -> None:
    SPEC_DIR.mkdir(parents=True, exist_ok=True)
    for filename, document in (
        ("envelope_v1_vectors.json", _envelope_vectors_document()),
        ("reducer_v1_vectors.json", _reducer_vectors_document()),
    ):
        path = SPEC_DIR / filename
        path.write_text(json.dumps(document, indent=2, sort_keys=False) + "\n")
        digest = hashlib.sha256(path.read_bytes()).hexdigest()
        print(f"{path.relative_to(SPEC_DIR.parents[1])}  sha256={digest}")


if __name__ == "__main__":
    main()
