"""Generate the frozen sync golden vectors in ``spec/sync/``.

Run once, by hand, and never again as part of a test or a CI job::

    cd backend && uv run python tools/generate_sync_vectors.py

The point of the vectors is that they are *frozen*: the Python codec and the
Dart codec both assert byte equality against the same committed file, so a
change on either side that the other did not make shows up as a failing test
rather than as two implementations quietly agreeing on something new.  A
generator wired into the test run would defeat that entirely — it would
regenerate the expectation to match whatever the Python side now does.

Re-running this script is therefore a deliberate protocol change.  Expect the
diff to be reviewed as one.
"""

from __future__ import annotations

import hashlib
import json
import struct
import sys
import uuid
from dataclasses import replace
from pathlib import Path
from typing import Any

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from nacl.signing import SigningKey  # noqa: E402

from app.sync.envelope import (  # noqa: E402
    BODY_OVERSIZE_MULTIPLE_BYTES,
    BODY_SIZE_CLASSES_BYTES,
    ENVELOPE_OVERHEAD_BYTES,
    HEADER_FIELD_LAYOUT,
    HEADER_LENGTH_BYTES,
    KNOWN_OP_CLASSES,
    OP_CLASS_COMPACTION,
    OP_CLASS_CONTENT,
    PAYLOAD_LENGTH_PREFIX_BYTES,
    SERVED_OP_CLASSES,
    SERVED_SUITES,
    SIGNATURE_LENGTH_BYTES,
    SIGNING_DOMAIN_OP_V1,
    SUITE_AEAD_V1,
    SUITE_PLAINTEXT_V1,
    OpHeader,
    build_envelope,
    derive_key_id,
    envelope_hash,
    frame_body,
)
from app.sync.ids import (  # noqa: E402
    JEEVES_WORKSPACE_NAMESPACE,
    USER_PREFERENCES_COLLECTION,
    implicit_workspace_id,
    preference_entity_id,
)
from app.sync.op_payload import FieldWrite, Hlc, OpPayload  # noqa: E402

SPEC_DIR = Path(__file__).resolve().parents[2] / "spec" / "sync"

FROZEN_NOTICE = (
    "FROZEN. Generated once by backend/tools/generate_sync_vectors.py and "
    "asserted byte-for-byte by both backend/tests/sync/ and app/test/sync/. "
    "Never regenerated by a test or by CI: regenerating is a protocol change."
)

# --- Fixed spec identities --------------------------------------------------

SPEC_USER_ID = "spec-user-1"
SPEC_OTHER_USER_ID = "spec-user-2"
WORKSPACE_ID = implicit_workspace_id(SPEC_USER_ID)
OTHER_WORKSPACE_ID = implicit_workspace_id(SPEC_OTHER_USER_ID)

KEY_LABELS = ("device_a", "device_b")


def _seed(label: str) -> bytes:
    return hashlib.sha256(f"jeeves/spec/sync/seed/{label}".encode()).digest()


def _member_id(label: str) -> uuid.UUID:
    return uuid.uuid5(JEEVES_WORKSPACE_NAMESPACE, f"spec/member/{label}")


def _op_id(name: str) -> uuid.UUID:
    return uuid.uuid5(JEEVES_WORKSPACE_NAMESPACE, f"spec/op/{name}")


SIGNING_KEYS = {label: SigningKey(_seed(label)) for label in KEY_LABELS}
MEMBER_IDS = {label: _member_id(label) for label in KEY_LABELS}

THEME_KEY = "theme"
THEME_ENTITY_ID = preference_entity_id(WORKSPACE_ID, THEME_KEY)

BASE_WALL_MS = 1_800_000_000_000


# --- Builders ---------------------------------------------------------------


def _header(
    *,
    op_id_name: str,
    key: str,
    author_seq: int,
    suite: int = SUITE_PLAINTEXT_V1,
    op_class: int = OP_CLASS_CONTENT,
    workspace_id: uuid.UUID = WORKSPACE_ID,
    prev_author_hash: bytes | None = None,
) -> OpHeader:
    sign_pk = bytes(SIGNING_KEYS[key].verify_key)
    return OpHeader(
        suite=suite,
        op_class=op_class,
        workspace_id=workspace_id,
        key_epoch=0,
        op_id=_op_id(op_id_name),
        author_member_id=MEMBER_IDS[key],
        author_key_id=derive_key_id(sign_pk),
        author_seq=author_seq,
        prev_author_hash=prev_author_hash or bytes(32),
    )


def _header_json(header: OpHeader) -> dict[str, Any]:
    return {
        "suite": header.suite,
        "op_class": header.op_class,
        "workspace_id": str(header.workspace_id),
        "key_epoch": header.key_epoch,
        "op_id": str(header.op_id),
        "author_member_id": str(header.author_member_id),
        "author_key_id_hex": header.author_key_id.hex(),
        "author_seq": header.author_seq,
        "prev_author_hash_hex": header.prev_author_hash.hex(),
        "observed_head_hex": header.observed_head.hex(),
        "nonce_hex": header.nonce.hex(),
    }


def _sized_payload(base: OpPayload, target_payload_length: int) -> OpPayload:
    """``base`` grown with an ASCII filler field to exactly the target length."""
    probe = replace(base, fields={**base.fields, "filler": FieldWrite(value="")})
    padding_needed = target_payload_length - len(probe.encode())
    if padding_needed < 0:
        raise ValueError(f"base payload already exceeds {target_payload_length} bytes")
    return replace(base, fields={**base.fields, "filler": FieldWrite(value="x" * padding_needed)})


def _positive(
    name: str,
    *,
    key: str,
    header: OpHeader,
    payload: bytes,
    note: str,
) -> dict[str, Any]:
    body = frame_body(payload)
    envelope = build_envelope(header, body, SIGNING_KEYS[key])
    return {
        "name": name,
        "note": note,
        "key": key,
        "header": _header_json(header),
        "header_hex": header.serialize().hex(),
        "payload_json": payload.decode("utf-8"),
        "payload_length_bytes": len(payload),
        "body_length_bytes": len(body),
        "body_hex": body.hex(),
        "signature_hex": envelope[-SIGNATURE_LENGTH_BYTES:].hex(),
        "envelope_hex": envelope.hex(),
        "envelope_sha256_hex": envelope_hash(envelope).hex(),
    }


def _negative(
    name: str,
    *,
    key: str,
    reason: str,
    envelope: bytes,
    note: str,
    expected_workspace_id: uuid.UUID = WORKSPACE_ID,
) -> dict[str, Any]:
    return {
        "name": name,
        "note": note,
        "key": key,
        "reason": reason,
        "expected_workspace_id": str(expected_workspace_id),
        "envelope_hex": envelope.hex(),
    }


def _theme_payload(*, key: str, value: str, wall_ms: int, counter: int = 0) -> OpPayload:
    return OpPayload(
        collection=USER_PREFERENCES_COLLECTION,
        entity_id=THEME_ENTITY_ID,
        hlc=Hlc.for_member(MEMBER_IDS[key], wall_ms, counter),
        fields={
            "key": FieldWrite(value=THEME_KEY),
            "value": FieldWrite(value=json.dumps(value)),
        },
    )


# --- Vector sets ------------------------------------------------------------


def _header_vectors() -> list[dict[str, Any]]:
    """Header-only vectors that pin each field to its offset.

    The probe is deliberately not a servable op: every field carries a distinct
    byte pattern so that a codec reading a field at the wrong offset produces
    visibly wrong bytes rather than a plausible-looking header.
    """
    all_zero = OpHeader(
        suite=0,
        op_class=0,
        workspace_id=uuid.UUID(int=0),
        key_epoch=0,
        op_id=uuid.UUID(int=0),
        author_member_id=uuid.UUID(int=0),
        author_key_id=bytes(8),
        author_seq=0,
    )
    probe = OpHeader(
        suite=0xA1,
        op_class=0xA2,
        workspace_id=uuid.UUID(bytes=b"\x11" * 16),
        key_epoch=0xB3B4B5B6,
        op_id=uuid.UUID(bytes=b"\x22" * 16),
        author_member_id=uuid.UUID(bytes=b"\x33" * 16),
        author_key_id=b"\x44" * 8,
        # Distinct in every byte that can be, and below 2^53 so a JSON reader
        # on a platform without a 64-bit integer type still round-trips it
        # exactly (see MAX_REPRESENTABLE_AUTHOR_SEQ on the Dart side).
        author_seq=0x001F2F3F4F5F6F7F,
        prev_author_hash=b"\x55" * 32,
        observed_head=b"\x66" * 32,
        nonce=b"\x77" * 24,
    )
    return [
        {
            "name": "all_zero_header",
            "note": "158 zero bytes — pins the header length itself.",
            "header": _header_json(all_zero),
            "header_hex": all_zero.serialize().hex(),
        },
        {
            "name": "distinct_field_probe",
            "note": "Every field a distinct byte pattern — pins every offset.",
            "header": _header_json(probe),
            "header_hex": probe.serialize().hex(),
        },
    ]


def _positive_vectors() -> list[dict[str, Any]]:
    vectors: list[dict[str, Any]] = []

    first_header = _header(op_id_name="set_theme_dark", key="device_a", author_seq=1)
    first = _positive(
        "content_set_preference",
        key="device_a",
        header=first_header,
        payload=_theme_payload(key="device_a", value="dark", wall_ms=BASE_WALL_MS).encode(),
        note="The smallest real op: one user_preferences write, body in the 256 class.",
    )
    vectors.append(first)

    chained_header = _header(
        op_id_name="set_theme_light",
        key="device_a",
        author_seq=2,
        prev_author_hash=bytes.fromhex(first["envelope_sha256_hex"]),
    )
    vectors.append(
        _positive(
            "content_chained_author_seq_2",
            key="device_a",
            header=chained_header,
            payload=_theme_payload(
                key="device_a", value="light", wall_ms=BASE_WALL_MS + 1000
            ).encode(),
            note=(
                "author_seq 2 with prev_author_hash = SHA-256 of "
                "content_set_preference's envelope — pins the per-author chain."
            ),
        )
    )

    vectors.append(
        _positive(
            "content_tombstone",
            key="device_b",
            header=_header(op_id_name="delete_theme", key="device_b", author_seq=1),
            payload=OpPayload(
                collection=USER_PREFERENCES_COLLECTION,
                entity_id=THEME_ENTITY_ID,
                hlc=Hlc.for_member(MEMBER_IDS["device_b"], BASE_WALL_MS + 2000),
                tombstone=True,
            ).encode(),
            note="Deletion is an op, never row absence: empty fields plus tombstone.",
        )
    )

    vectors.append(
        _positive(
            "content_per_field_hlc",
            key="device_a",
            header=_header(op_id_name="per_field_hlc", key="device_a", author_seq=3),
            payload=OpPayload(
                collection=USER_PREFERENCES_COLLECTION,
                entity_id=THEME_ENTITY_ID,
                hlc=Hlc.for_member(MEMBER_IDS["device_a"], BASE_WALL_MS + 3000),
                fields={
                    "key": FieldWrite(value=THEME_KEY),
                    "value": FieldWrite(
                        value='"solarized"',
                        hlc=Hlc.for_member(MEMBER_IDS["device_b"], BASE_WALL_MS - 5000),
                    ),
                },
            ).encode(),
            note=(
                "Per-field HLC capability: format now, populated only by "
                "compaction ops (#555) re-asserting original clocks."
            ),
        )
    )

    for index, size_class in enumerate(BODY_SIZE_CLASSES_BYTES):
        vectors.append(
            _positive(
                f"content_body_size_class_{size_class}",
                key="device_a",
                header=_header(
                    op_id_name=f"size_class_{size_class}", key="device_a", author_seq=10 + index
                ),
                payload=_sized_payload(
                    _theme_payload(key="device_a", value="dark", wall_ms=BASE_WALL_MS),
                    size_class - 36,
                ).encode(),
                note=f"Body padded to the {size_class}-byte size class, 32 padding bytes.",
            )
        )

    oversize_body_length = 2 * BODY_OVERSIZE_MULTIPLE_BYTES
    vectors.append(
        _positive(
            "content_body_oversize_32768",
            key="device_a",
            header=_header(op_id_name="oversize", key="device_a", author_seq=20),
            payload=_sized_payload(
                _theme_payload(key="device_a", value="dark", wall_ms=BASE_WALL_MS),
                oversize_body_length - 36,
            ).encode(),
            note=(
                "Above the largest size class a body rounds up to the next "
                "16 KiB multiple, with no hard cap."
            ),
        )
    )

    return vectors


def _negative_vectors() -> list[dict[str, Any]]:
    payload = _theme_payload(key="device_a", value="dark", wall_ms=BASE_WALL_MS).encode()
    body = frame_body(payload)
    vectors: list[dict[str, Any]] = []

    vectors.append(
        _negative(
            "unknown_suite",
            key="device_a",
            reason="unsupported_suite",
            envelope=build_envelope(
                _header(op_id_name="unknown_suite", key="device_a", author_seq=1, suite=0x7F),
                body,
                SIGNING_KEYS["device_a"],
            ),
            note="Suite 0x7F is not a value the protocol names. Fail closed (F21).",
        )
    )
    vectors.append(
        _negative(
            "unknown_op_class",
            key="device_a",
            reason="unsupported_op_class",
            envelope=build_envelope(
                _header(op_id_name="unknown_op_class", key="device_a", author_seq=1, op_class=9),
                body,
                SIGNING_KEYS["device_a"],
            ),
            note="op_class 9 is outside 1-5. Fail closed.",
        )
    )
    vectors.append(
        _negative(
            "unimplemented_op_class_compaction",
            key="device_a",
            reason="unsupported_op_class",
            envelope=build_envelope(
                _header(
                    op_id_name="unimplemented_op_class",
                    key="device_a",
                    author_seq=1,
                    op_class=OP_CLASS_COMPACTION,
                ),
                body,
                SIGNING_KEYS["device_a"],
            ),
            note=(
                "op_class 4 is a named class this slice does not implement. It "
                "quarantines on the same surface as an unknown value; #555 turns "
                "this into a positive vector."
            ),
        )
    )

    valid = build_envelope(
        _header(op_id_name="set_theme_dark", key="device_a", author_seq=1),
        body,
        SIGNING_KEYS["device_a"],
    )
    vectors.append(
        _negative(
            "truncated_header",
            key="device_a",
            reason="truncated_envelope",
            envelope=valid[: HEADER_LENGTH_BYTES - 1],
            note=f"One byte short of the {HEADER_LENGTH_BYTES}-byte header.",
        )
    )
    vectors.append(
        _negative(
            "truncated_envelope_no_body",
            key="device_a",
            reason="truncated_envelope",
            envelope=valid[:ENVELOPE_OVERHEAD_BYTES],
            note=f"Exactly the {ENVELOPE_OVERHEAD_BYTES}-byte overhead: no body at all.",
        )
    )
    vectors.append(
        _negative(
            "bad_signature",
            key="device_a",
            reason="bad_signature",
            envelope=valid[:-1] + bytes([valid[-1] ^ 0x01]),
            note="Last signature byte flipped; header and body untouched.",
        )
    )

    padding_start = PAYLOAD_LENGTH_PREFIX_BYTES + len(payload)
    tampered_padding = bytearray(body)
    tampered_padding[padding_start] = 0x01
    vectors.append(
        _negative(
            "non_zero_padding",
            key="device_a",
            reason="non_zero_padding",
            envelope=build_envelope(
                _header(op_id_name="non_zero_padding", key="device_a", author_seq=1),
                bytes(tampered_padding),
                SIGNING_KEYS["device_a"],
            ),
            note=(
                f"The non-zero byte sits at offset {padding_start} = "
                "4 + payload_len, the *first* padding position, so an "
                "off-by-one in the padding scan cannot pass this vector. "
                "Signed over the tampered body, so only the padding rule fires."
            ),
        )
    )

    illegal_length = 300
    illegal_body = bytearray(struct.pack(">I", len(payload)) + payload)
    illegal_body.extend(bytes(illegal_length - len(illegal_body)))
    vectors.append(
        _negative(
            "invalid_padded_length",
            key="device_a",
            reason="invalid_body_length",
            envelope=build_envelope(
                _header(op_id_name="invalid_padded_length", key="device_a", author_seq=1),
                bytes(illegal_body),
                SIGNING_KEYS["device_a"],
            ),
            note=(
                f"{illegal_length}-byte body: neither a size class nor a "
                f"{BODY_OVERSIZE_MULTIPLE_BYTES}-byte multiple."
            ),
        )
    )

    overrun_body = bytearray(body)
    overrun_body[:PAYLOAD_LENGTH_PREFIX_BYTES] = struct.pack(">I", len(body))
    vectors.append(
        _negative(
            "payload_overruns_body",
            key="device_a",
            reason="payload_overruns_body",
            envelope=build_envelope(
                _header(op_id_name="payload_overruns_body", key="device_a", author_seq=1),
                bytes(overrun_body),
                SIGNING_KEYS["device_a"],
            ),
            note=(
                "payload_len is the whole body length, so 4 + payload_len > "
                "body_len. The frame must be rejected before any byte of it is "
                "read as a payload."
            ),
        )
    )

    uppercase_payload = json.dumps(
        {
            "collection": USER_PREFERENCES_COLLECTION,
            "id": str(THEME_ENTITY_ID),
            "fields": {"value": {"v": '"dark"'}},
            "hlc": [BASE_WALL_MS, 0, MEMBER_IDS["device_a"].hex.upper()],
        },
        separators=(",", ":"),
    ).encode("utf-8")
    vectors.append(
        _negative(
            "uppercase_member_id_hex",
            key="device_a",
            reason="malformed_member_id_hex",
            envelope=build_envelope(
                _header(op_id_name="uppercase_member_id", key="device_a", author_seq=1),
                frame_body(uppercase_payload),
                SIGNING_KEYS["device_a"],
            ),
            note=(
                "HLC member ids are exactly 32 lowercase hex characters. The "
                "tie-break is a lexicographic string compare, so an uppercase "
                "id would order differently — codecs reject rather than "
                "normalise."
            ),
        )
    )

    malformed_entity_id_payload = json.dumps(
        {
            "collection": USER_PREFERENCES_COLLECTION,
            "id": str(THEME_ENTITY_ID).replace("-", ""),
            "fields": {"value": {"v": '"dark"'}},
            "hlc": [BASE_WALL_MS, 0, MEMBER_IDS["device_a"].hex],
        },
        separators=(",", ":"),
    ).encode("utf-8")
    vectors.append(
        _negative(
            "malformed_entity_id",
            key="device_a",
            reason="malformed_payload",
            envelope=build_envelope(
                _header(op_id_name="malformed_entity_id", key="device_a", author_seq=1),
                frame_body(malformed_entity_id_payload),
                SIGNING_KEYS["device_a"],
            ),
            note=(
                "The right 32 hex digits, dashes removed.  Python's `uuid.UUID` "
                "accepts this spelling and the Dart codec's `uuidToBytes` does "
                "not, so it is exactly the shape the two codecs used to "
                "disagree about.  Both now require the canonical lowercase "
                "8-4-4-4-12 form and reject the rest rather than normalising, "
                "as they do for an HLC member id."
            ),
        )
    )

    vectors.append(
        _negative(
            "workspace_mismatch",
            key="device_a",
            reason="workspace_mismatch",
            envelope=build_envelope(
                _header(
                    op_id_name="workspace_mismatch",
                    key="device_a",
                    author_seq=1,
                    workspace_id=OTHER_WORKSPACE_ID,
                ),
                body,
                SIGNING_KEYS["device_a"],
            ),
            note=(
                "Header workspace disagrees with the stream it arrived in: a "
                "server-integrity event, not a filtered row (F6). The "
                "plaintext-era analogue of 'AEAD failure is an alarm'."
            ),
        )
    )

    return vectors


def _envelope_vectors_document() -> dict[str, Any]:
    return {
        "$frozen": FROZEN_NOTICE,
        "protocol": {
            "header_length_bytes": HEADER_LENGTH_BYTES,
            "signature_length_bytes": SIGNATURE_LENGTH_BYTES,
            "envelope_overhead_bytes": ENVELOPE_OVERHEAD_BYTES,
            "signing_domain": SIGNING_DOMAIN_OP_V1.decode("ascii"),
            "signing_domain_hex": SIGNING_DOMAIN_OP_V1.hex(),
            "header_field_layout": [
                {"name": name, "offset": offset, "length_bytes": length}
                for name, offset, length in HEADER_FIELD_LAYOUT
            ],
            "suites": {
                "plaintext_v1": SUITE_PLAINTEXT_V1,
                "aead_v1_reserved": SUITE_AEAD_V1,
            },
            "served_suites": sorted(SERVED_SUITES),
            "op_classes": {
                "content": 1,
                "control": 2,
                "suggestion": 3,
                "compaction": 4,
                "prune": 5,
            },
            "known_op_classes": sorted(KNOWN_OP_CLASSES),
            "served_op_classes": sorted(SERVED_OP_CLASSES),
            "payload_length_prefix_bytes": PAYLOAD_LENGTH_PREFIX_BYTES,
            "body_size_classes_bytes": list(BODY_SIZE_CLASSES_BYTES),
            "body_oversize_multiple_bytes": BODY_OVERSIZE_MULTIPLE_BYTES,
            "workspace_namespace_uuid": str(JEEVES_WORKSPACE_NAMESPACE),
        },
        "identities": {
            "user_id": SPEC_USER_ID,
            "workspace_id": str(WORKSPACE_ID),
            "other_user_id": SPEC_OTHER_USER_ID,
            "other_workspace_id": str(OTHER_WORKSPACE_ID),
            "preference_key": THEME_KEY,
            "preference_entity_id": str(THEME_ENTITY_ID),
            "keys": [
                {
                    "label": label,
                    "member_id": str(MEMBER_IDS[label]),
                    "seed_hex": _seed(label).hex(),
                    "sign_pk_hex": bytes(SIGNING_KEYS[label].verify_key).hex(),
                    "key_id_hex": derive_key_id(bytes(SIGNING_KEYS[label].verify_key)).hex(),
                }
                for label in KEY_LABELS
            ],
        },
        "header_vectors": _header_vectors(),
        "vectors": _positive_vectors(),
        "negative_vectors": _negative_vectors(),
    }


# --- Reducer vectors --------------------------------------------------------

_HARNESS_COLLECTION = "harness_docs"
_DOC_ID = str(uuid.uuid5(JEEVES_WORKSPACE_NAMESPACE, "spec/entity/harness_doc"))
_MEMBER_A = MEMBER_IDS["device_a"].hex
_MEMBER_B = MEMBER_IDS["device_b"].hex
# device_a and device_b must sort in a known direction for the tie-break case.
_LOWER_MEMBER, _HIGHER_MEMBER = sorted((_MEMBER_A, _MEMBER_B))


def _reduce_op(
    *,
    author: str,
    collection: str = _HARNESS_COLLECTION,
    entity_id: str = _DOC_ID,
    hlc: list[Any],
    fields: dict[str, Any] | None = None,
    tombstone: bool = False,
) -> dict[str, Any]:
    payload: dict[str, Any] = {
        "collection": collection,
        "id": entity_id,
        "fields": fields or {},
        "hlc": hlc,
    }
    if tombstone:
        payload["tombstone"] = True
    return {"author_member_id_hex": author, "payload": payload}


def _reducer_vectors_document() -> dict[str, Any]:
    t = BASE_WALL_MS
    cases: list[dict[str, Any]] = [
        {
            "name": "single_write",
            "note": "The base case: one field, one HLC, one live entity.",
            "ops": [
                _reduce_op(
                    author=_MEMBER_A,
                    hlc=[t, 0, _MEMBER_A],
                    fields={"a": {"v": "first"}},
                )
            ],
            "expected_entities": {_HARNESS_COLLECTION: {_DOC_ID: {"a": "first"}}},
            "expected_quarantine_reasons": [],
        },
        {
            "name": "same_field_newer_hlc_wins",
            "note": "Applied in HLC order.",
            "ops": [
                _reduce_op(author=_MEMBER_A, hlc=[t, 0, _MEMBER_A], fields={"a": {"v": "older"}}),
                _reduce_op(
                    author=_MEMBER_B,
                    hlc=[t + 1000, 0, _MEMBER_B],
                    fields={"a": {"v": "newer"}},
                ),
            ],
            "expected_entities": {_HARNESS_COLLECTION: {_DOC_ID: {"a": "newer"}}},
            "expected_quarantine_reasons": [],
        },
        {
            "name": "same_field_older_hlc_loses_out_of_order",
            "note": "Same two ops, reversed arrival. Reduction is order-independent.",
            "ops": [
                _reduce_op(
                    author=_MEMBER_B,
                    hlc=[t + 1000, 0, _MEMBER_B],
                    fields={"a": {"v": "newer"}},
                ),
                _reduce_op(author=_MEMBER_A, hlc=[t, 0, _MEMBER_A], fields={"a": {"v": "older"}}),
            ],
            "expected_entities": {_HARNESS_COLLECTION: {_DOC_ID: {"a": "newer"}}},
            "expected_quarantine_reasons": [],
        },
        {
            "name": "field_grain_concurrent_different_fields_both_survive",
            "note": "AC 5: concurrent edits to different fields of one row both survive.",
            "ops": [
                _reduce_op(author=_MEMBER_A, hlc=[t, 0, _MEMBER_A], fields={"a": {"v": "from_a"}}),
                _reduce_op(author=_MEMBER_B, hlc=[t, 0, _MEMBER_B], fields={"b": {"v": "from_b"}}),
            ],
            "expected_entities": {_HARNESS_COLLECTION: {_DOC_ID: {"a": "from_a", "b": "from_b"}}},
            "expected_quarantine_reasons": [],
        },
        {
            "name": "equal_hlc_is_idempotent",
            "note": "A pulled echo of one's own op re-applies to the same state.",
            "ops": [
                _reduce_op(author=_MEMBER_A, hlc=[t, 0, _MEMBER_A], fields={"a": {"v": "once"}}),
                _reduce_op(author=_MEMBER_A, hlc=[t, 0, _MEMBER_A], fields={"a": {"v": "once"}}),
            ],
            "expected_entities": {_HARNESS_COLLECTION: {_DOC_ID: {"a": "once"}}},
            "expected_quarantine_reasons": [],
        },
        {
            "name": "member_id_breaks_the_tie",
            "note": (
                "Equal wall_ms and counter: the member id decides, by "
                "lexicographic compare of the 32-hex form."
            ),
            "ops": [
                _reduce_op(
                    author=_LOWER_MEMBER,
                    hlc=[t, 0, _LOWER_MEMBER],
                    fields={"a": {"v": "lower_member"}},
                ),
                _reduce_op(
                    author=_HIGHER_MEMBER,
                    hlc=[t, 0, _HIGHER_MEMBER],
                    fields={"a": {"v": "higher_member"}},
                ),
            ],
            "expected_entities": {_HARNESS_COLLECTION: {_DOC_ID: {"a": "higher_member"}}},
            "expected_quarantine_reasons": [],
        },
        {
            "name": "tombstone_absorbs_older_write",
            "note": "A field write older than the tombstone stays hidden.",
            "ops": [
                _reduce_op(author=_MEMBER_A, hlc=[t, 0, _MEMBER_A], fields={"a": {"v": "doomed"}}),
                _reduce_op(author=_MEMBER_B, hlc=[t + 1000, 0, _MEMBER_B], tombstone=True),
            ],
            "expected_entities": {_HARNESS_COLLECTION: {}},
            "expected_quarantine_reasons": [],
        },
        {
            "name": "tombstone_resurrection_by_newer_write",
            "note": (
                "The mirror case: a field write newer than the tombstone applies "
                "and revives the entity, with only that field live."
            ),
            "ops": [
                _reduce_op(author=_MEMBER_A, hlc=[t, 0, _MEMBER_A], fields={"a": {"v": "doomed"}}),
                _reduce_op(author=_MEMBER_B, hlc=[t + 1000, 0, _MEMBER_B], tombstone=True),
                _reduce_op(
                    author=_MEMBER_A,
                    hlc=[t + 2000, 0, _MEMBER_A],
                    fields={"b": {"v": "revived"}},
                ),
            ],
            "expected_entities": {_HARNESS_COLLECTION: {_DOC_ID: {"b": "revived"}}},
            "expected_quarantine_reasons": [],
        },
        {
            "name": "per_field_hlc_from_another_member_in_the_past_applies",
            "note": (
                "F15 scoping, as ruled for this slice: the future-clock and "
                "hlc-member-equals-author guards are scoped to the op-level HLC "
                "*only*. A per-field HLC naming a different member at an older "
                "wall_ms is legal — that is exactly what a compaction op (#555) "
                "will carry — so it applies rather than quarantining."
            ),
            "ops": [
                _reduce_op(
                    author=_MEMBER_A,
                    hlc=[t + 5000, 0, _MEMBER_A],
                    fields={
                        "a": {"v": "reasserted", "hlc": [t - 60000, 7, _MEMBER_B]},
                        "b": {"v": "fresh"},
                    },
                )
            ],
            "expected_entities": {
                _HARNESS_COLLECTION: {_DOC_ID: {"a": "reasserted", "b": "fresh"}}
            },
            "expected_quarantine_reasons": [],
        },
        {
            "name": "per_field_hlc_loses_to_a_newer_stored_clock",
            "note": (
                "The per-field exemption is from the *guards*, not from LWW: a "
                "re-asserted older clock still loses to a newer stored one."
            ),
            "ops": [
                _reduce_op(
                    author=_MEMBER_B,
                    hlc=[t + 1000, 0, _MEMBER_B],
                    fields={"a": {"v": "current"}},
                ),
                _reduce_op(
                    author=_MEMBER_A,
                    hlc=[t + 5000, 0, _MEMBER_A],
                    fields={"a": {"v": "stale_reassert", "hlc": [t, 0, _MEMBER_A]}},
                ),
            ],
            "expected_entities": {_HARNESS_COLLECTION: {_DOC_ID: {"a": "current"}}},
            "expected_quarantine_reasons": [],
        },
        {
            "name": "op_level_hlc_in_the_future_quarantines",
            "note": (
                "F15: an unbounded wall_ms would pin a field against every "
                "future edit. Beyond the skew bound the op quarantines whole."
            ),
            "ops": [
                _reduce_op(
                    author=_MEMBER_A,
                    hlc=[t + 3_600_000, 0, _MEMBER_A],
                    fields={"a": {"v": "from_the_future"}},
                )
            ],
            "expected_entities": {_HARNESS_COLLECTION: {}},
            "expected_quarantine_reasons": ["hlc_in_the_future"],
        },
        {
            "name": "op_level_hlc_member_not_author_quarantines",
            "note": (
                "F15: the op-level HLC member must be the header's author, or a "
                "member could win tie-breaks under someone else's identity."
            ),
            "ops": [
                _reduce_op(
                    author=_MEMBER_A,
                    hlc=[t, 0, _MEMBER_B],
                    fields={"a": {"v": "impersonated"}},
                )
            ],
            "expected_entities": {_HARNESS_COLLECTION: {}},
            "expected_quarantine_reasons": ["hlc_member_is_not_author"],
        },
        {
            "name": "quarantined_op_does_not_stop_the_stream",
            "note": "A bad op is set aside and surfaced; the next valid op still applies.",
            "ops": [
                _reduce_op(
                    author=_MEMBER_A,
                    hlc=[t + 3_600_000, 0, _MEMBER_A],
                    fields={"a": {"v": "from_the_future"}},
                ),
                _reduce_op(author=_MEMBER_B, hlc=[t, 0, _MEMBER_B], fields={"a": {"v": "sane"}}),
            ],
            "expected_entities": {_HARNESS_COLLECTION: {_DOC_ID: {"a": "sane"}}},
            "expected_quarantine_reasons": ["hlc_in_the_future"],
        },
    ]
    return {
        "$frozen": FROZEN_NOTICE,
        "local_now_ms": BASE_WALL_MS,
        "future_skew_bound_ms": 300_000,
        "$note": (
            "Ops here are payload-level, paired with the header author the "
            "reducer's guards check against. Envelope framing is "
            "envelope_v1_vectors.json's job. 'expected_entities' lists the live "
            "fields of every live entity after applying the ops in order; an "
            "entity with no live field is absent from the map."
        ),
        "cases": cases,
    }


def main() -> None:
    SPEC_DIR.mkdir(parents=True, exist_ok=True)
    for filename, document in (
        ("envelope_v1_vectors.json", _envelope_vectors_document()),
        ("reducer_v1_vectors.json", _reducer_vectors_document()),
    ):
        path = SPEC_DIR / filename
        path.write_text(json.dumps(document, indent=2, sort_keys=False) + "\n")
        digest = hashlib.sha256(path.read_bytes()).hexdigest()
        print(f"{path.relative_to(SPEC_DIR.parents[1])}  sha256={digest}")


if __name__ == "__main__":
    main()
